.TH "/home/parametheus/repo/QKlipper/QKlipperFile Directory Reference" 3 "Version 0.2" "QKlipper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/parametheus/repo/QKlipper/QKlipperFile Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBqklipperfile\&.cpp\fP"
.br
.ti -1c
.RI "file \fBqklipperfile\&.h\fP"
.br
.ti -1c
.RI "file \fBqklippermetadata\&.h\fP"
.br
.ti -1c
.RI "file \fBqklipperthumbnail\&.h\fP"
.br
.in -1c
