.TH "/home/parametheus/repo/QKlipper/QKlipperMessage Directory Reference" 3 "Version 0.2" "QKlipper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/parametheus/repo/QKlipper/QKlipperMessage Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBqklippermessage\&.cpp\fP"
.br
.ti -1c
.RI "file \fBqklippermessage\&.h\fP"
.br
.in -1c
