.TH "/home/parametheus/repo/QKlipper/main.cpp" 3 "Version 0.2" "QKlipper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/parametheus/repo/QKlipper/main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <QCoreApplication>\fP
.br
\fC#include 'QKlipperInstance/qklipperinstance\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.SH "Author"
.PP 
Generated automatically by Doxygen for QKlipper from the source code\&.
