.TH "md__2home_2parametheus_2repo_2QKlipper_2README" 3 "Version 0.2" "QKlipper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__2home_2parametheus_2repo_2QKlipper_2README \- README 
.PP
 
.SH "QKlipper"
.PP
Qt based Klipper/Moonraker library (ALPHA - convenience methods still being ported over the next couple of days as well as QML compatability)
.SS "Usage"
.IP "\(bu" 2
Add QKlipper files to your Qt project
.IP "\(bu" 2
Add Qt dependencies 
.PP
.nf
QT += core network websockets

.fi
.PP

.IP "\(bu" 2
Include \fBQKlipperInstance\fP 
.PP
.nf
#include "QKlipper/QKlipperInstance/qklipperinstance\&.h"

.fi
.PP

.PP
.PP
Local connections 
.PP
.nf
//Creating a local instance
QKlipperInstance *instance = new QKlipperInstance();
instance\->setName("QKlipper Test");

//address and port for non\-rpc calls
instance\->setPort(7125);
instance\->setAddress("localhost"); //do not include http

//instance location is required for local connections
instance\->setInstanceLocation("/home/parametheus/printer_data");
instance\->setAutoConnect(true);

instance\->init();

.fi
.PP
 Local connections require \fCsetInstanceLoction\fP to be called with the fully qualified path of the klipper installation\&.
.PP
Remote connections 
.PP
.nf
//Creating a remote instance
QKlipperInstance *instance = new QKlipperInstance();
instance\->setName("QKlipper Test");

//address and port for klipper instance
instance\->setPort(7125);
instance\->setAddress("artifex\&.local"); //do not include http
instance\->setAutoConnect(true);

instance\->init();

.fi
.PP
.PP
Once \fCinit\fP has been called, it is then possible to connect to the various signals provided by \fBQKlipperServer\fP, \fBQKlipperPrinter\fP and \fBQKlipperSystem\fP\&. These classes also provide various convenience functions for controlling the different aspects of the Klipper instance\&. \fBQKlipperConsole\fP also provides methods for nearly the entire Moonraker API and supports sending custom messages (custom parser hooks coming soon)\&.
.PP
.PP
.nf
QKlipperPrinter *printer = instance\->printer();
printer\->toolhead()\->home();
.fi
.PP
 
