.TH "QKlipperCanBus" 3 "Version 0.2" "QKlipper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QKlipperCanBus \- Filled by machine\&.peripherals\&.canbus\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qklippercanbus\&.h>\fP
.PP
Inherits QObject\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBsetInterfaces\fP (const QList< \fBQKlipperCanBusInterface\fP > &\fBinterfaces\fP)"
.br
.ti -1c
.RI "void \fBsetDevices\fP (const \fBQKlipperCanBusDeviceMap\fP &\fBdevices\fP)"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBinterfacesChanged\fP ()"
.br
.ti -1c
.RI "void \fBdevicesChanged\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQKlipperCanBus\fP (QObject *parent=nullptr)"
.br
.ti -1c
.RI "QList< \fBQKlipperCanBusInterface\fP > \fBinterfaces\fP () const"
.br
.ti -1c
.RI "\fBQKlipperCanBusDeviceMap\fP \fBdevices\fP () const"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "QList< \fBQKlipperCanBusInterface\fP > \fBinterfaces\fP"
.br
.ti -1c
.RI "\fBQKlipperCanBusDeviceMap\fP \fBdevices\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Filled by machine\&.peripherals\&.canbus\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QKlipperCanBus::QKlipperCanBus (QObject * parent = \fCnullptr\fP)\fC [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBQKlipperCanBusDeviceMap\fP QKlipperCanBus::devices () const"

.SS "void QKlipperCanBus::devicesChanged ()\fC [signal]\fP"

.SS "QList< \fBQKlipperCanBusInterface\fP > QKlipperCanBus::interfaces () const"

.SS "void QKlipperCanBus::interfacesChanged ()\fC [signal]\fP"

.SS "void QKlipperCanBus::setDevices (const \fBQKlipperCanBusDeviceMap\fP & devices)\fC [slot]\fP"

.SS "void QKlipperCanBus::setInterfaces (const QList< \fBQKlipperCanBusInterface\fP > & interfaces)\fC [slot]\fP"

.SH "Property Documentation"
.PP 
.SS "\fBQKlipperCanBusDeviceMap\fP QKlipperCanBus::devices\fC [read]\fP, \fC [write]\fP"

.SS "QList<\fBQKlipperCanBusInterface\fP> QKlipperCanBus::interfaces\fC [read]\fP, \fC [write]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for QKlipper from the source code\&.
