.TH "/home/parametheus/repo/QKlipper/QKlipperConsole/qklipperconsole.cpp" 3 "Version 0.2" "QKlipper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/parametheus/repo/QKlipper/QKlipperConsole/qklipperconsole.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'qklipperconsole\&.h'\fP
.br
\fC#include 'qeventloop\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QKlipper from the source code\&.
