.TH "QKlipperMoonrakerStatsEntry" 3 "Version 0.2" "QKlipper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QKlipperMoonrakerStatsEntry \- Filled by machine\&.proc_stats\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qklippermoonrakerstatsentry\&.h>\fP
.PP
Inherits QObject\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBsetTime\fP (qreal \fBtime\fP)"
.br
.ti -1c
.RI "void \fBsetCpuUsage\fP (qreal \fBcpuUsage\fP)"
.br
.ti -1c
.RI "void \fBsetMemory\fP (qreal \fBmemory\fP)"
.br
.ti -1c
.RI "void \fBsetMemoryUnits\fP (const QString &\fBmemoryUnits\fP)"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBtimeChanged\fP ()"
.br
.ti -1c
.RI "void \fBcpuUsageChanged\fP ()"
.br
.ti -1c
.RI "void \fBmemoryChanged\fP ()"
.br
.ti -1c
.RI "void \fBmemoryUnitsChanged\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQKlipperMoonrakerStatsEntry\fP (QObject *parent=nullptr)"
.br
.ti -1c
.RI "\fBQKlipperMoonrakerStatsEntry\fP (const \fBQKlipperMoonrakerStatsEntry\fP &value)"
.br
.ti -1c
.RI "\fBQKlipperMoonrakerStatsEntry\fP (\fBQKlipperMoonrakerStatsEntry\fP &&value)"
.br
.ti -1c
.RI "\fBQKlipperMoonrakerStatsEntry\fP & \fBoperator=\fP (const \fBQKlipperMoonrakerStatsEntry\fP &value)"
.br
.ti -1c
.RI "\fBQKlipperMoonrakerStatsEntry\fP & \fBoperator=\fP (\fBQKlipperMoonrakerStatsEntry\fP &&value)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBQKlipperMoonrakerStatsEntry\fP &value)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (\fBQKlipperMoonrakerStatsEntry\fP &&value)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBQKlipperMoonrakerStatsEntry\fP &value)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (\fBQKlipperMoonrakerStatsEntry\fP &&value)"
.br
.ti -1c
.RI "qreal \fBtime\fP () const"
.br
.ti -1c
.RI "qreal \fBcpuUsage\fP () const"
.br
.ti -1c
.RI "qreal \fBmemory\fP () const"
.br
.ti -1c
.RI "QString \fBmemoryUnits\fP () const"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "qreal \fBtime\fP"
.br
.ti -1c
.RI "qreal \fBcpuUsage\fP"
.br
.ti -1c
.RI "qreal \fBmemory\fP"
.br
.ti -1c
.RI "QString \fBmemoryUnits\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Filled by machine\&.proc_stats\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QKlipperMoonrakerStatsEntry::QKlipperMoonrakerStatsEntry (QObject * parent = \fCnullptr\fP)\fC [explicit]\fP"

.SS "QKlipperMoonrakerStatsEntry::QKlipperMoonrakerStatsEntry (const \fBQKlipperMoonrakerStatsEntry\fP & value)"

.SS "QKlipperMoonrakerStatsEntry::QKlipperMoonrakerStatsEntry (\fBQKlipperMoonrakerStatsEntry\fP && value)"

.SH "Member Function Documentation"
.PP 
.SS "qreal QKlipperMoonrakerStatsEntry::cpuUsage () const"

.SS "void QKlipperMoonrakerStatsEntry::cpuUsageChanged ()\fC [signal]\fP"

.SS "qreal QKlipperMoonrakerStatsEntry::memory () const"

.SS "void QKlipperMoonrakerStatsEntry::memoryChanged ()\fC [signal]\fP"

.SS "QString QKlipperMoonrakerStatsEntry::memoryUnits () const"

.SS "void QKlipperMoonrakerStatsEntry::memoryUnitsChanged ()\fC [signal]\fP"

.SS "bool QKlipperMoonrakerStatsEntry::operator!= (const \fBQKlipperMoonrakerStatsEntry\fP & value)"

.SS "bool QKlipperMoonrakerStatsEntry::operator!= (\fBQKlipperMoonrakerStatsEntry\fP && value)"

.SS "\fBQKlipperMoonrakerStatsEntry\fP & QKlipperMoonrakerStatsEntry::operator= (const \fBQKlipperMoonrakerStatsEntry\fP & value)"

.SS "\fBQKlipperMoonrakerStatsEntry\fP & QKlipperMoonrakerStatsEntry::operator= (\fBQKlipperMoonrakerStatsEntry\fP && value)"

.SS "bool QKlipperMoonrakerStatsEntry::operator== (const \fBQKlipperMoonrakerStatsEntry\fP & value)"

.SS "bool QKlipperMoonrakerStatsEntry::operator== (\fBQKlipperMoonrakerStatsEntry\fP && value)"

.SS "void QKlipperMoonrakerStatsEntry::setCpuUsage (qreal cpuUsage)\fC [slot]\fP"

.SS "void QKlipperMoonrakerStatsEntry::setMemory (qreal memory)\fC [slot]\fP"

.SS "void QKlipperMoonrakerStatsEntry::setMemoryUnits (const QString & memoryUnits)\fC [slot]\fP"

.SS "void QKlipperMoonrakerStatsEntry::setTime (qreal time)\fC [slot]\fP"

.SS "qreal QKlipperMoonrakerStatsEntry::time () const"

.SS "void QKlipperMoonrakerStatsEntry::timeChanged ()\fC [signal]\fP"

.SH "Property Documentation"
.PP 
.SS "qreal QKlipperMoonrakerStatsEntry::cpuUsage\fC [read]\fP, \fC [write]\fP"

.SS "qreal QKlipperMoonrakerStatsEntry::memory\fC [read]\fP, \fC [write]\fP"

.SS "QString QKlipperMoonrakerStatsEntry::memoryUnits\fC [read]\fP, \fC [write]\fP"

.SS "qreal QKlipperMoonrakerStatsEntry::time\fC [read]\fP, \fC [write]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for QKlipper from the source code\&.
