.TH "QKlipperThrottleState" 3 "Version 0.2" "QKlipper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QKlipperThrottleState \- Filled by machine\&.proc_stats\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qklipperthrottlestate\&.h>\fP
.PP
Inherits QObject\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBsetBits\fP (qint32 \fBbits\fP)"
.br
.ti -1c
.RI "void \fBsetFlags\fP (const QStringList &\fBflags\fP)"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBbitsChanged\fP ()"
.br
.ti -1c
.RI "void \fBflagsChanged\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQKlipperThrottleState\fP (QObject *parent=nullptr)"
.br
.ti -1c
.RI "\fBQKlipperThrottleState\fP (const \fBQKlipperThrottleState\fP &value)"
.br
.ti -1c
.RI "\fBQKlipperThrottleState\fP (\fBQKlipperThrottleState\fP &&value)"
.br
.ti -1c
.RI "\fBQKlipperThrottleState\fP & \fBoperator=\fP (const \fBQKlipperThrottleState\fP &value)"
.br
.ti -1c
.RI "\fBQKlipperThrottleState\fP & \fBoperator=\fP (\fBQKlipperThrottleState\fP &&value)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBQKlipperThrottleState\fP &value)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (\fBQKlipperThrottleState\fP &&value)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBQKlipperThrottleState\fP &value)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (\fBQKlipperThrottleState\fP &&value)"
.br
.ti -1c
.RI "qint32 \fBbits\fP () const"
.br
.ti -1c
.RI "QStringList \fBflags\fP () const"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "qint32 \fBbits\fP"
.br
.ti -1c
.RI "QStringList \fBflags\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Filled by machine\&.proc_stats\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QKlipperThrottleState::QKlipperThrottleState (QObject * parent = \fCnullptr\fP)\fC [explicit]\fP"

.SS "QKlipperThrottleState::QKlipperThrottleState (const \fBQKlipperThrottleState\fP & value)"

.SS "QKlipperThrottleState::QKlipperThrottleState (\fBQKlipperThrottleState\fP && value)"

.SH "Member Function Documentation"
.PP 
.SS "qint32 QKlipperThrottleState::bits () const"

.SS "void QKlipperThrottleState::bitsChanged ()\fC [signal]\fP"

.SS "QStringList QKlipperThrottleState::flags () const"

.SS "void QKlipperThrottleState::flagsChanged ()\fC [signal]\fP"

.SS "bool QKlipperThrottleState::operator!= (const \fBQKlipperThrottleState\fP & value)"

.SS "bool QKlipperThrottleState::operator!= (\fBQKlipperThrottleState\fP && value)"

.SS "\fBQKlipperThrottleState\fP & QKlipperThrottleState::operator= (const \fBQKlipperThrottleState\fP & value)"

.SS "\fBQKlipperThrottleState\fP & QKlipperThrottleState::operator= (\fBQKlipperThrottleState\fP && value)"

.SS "bool QKlipperThrottleState::operator== (const \fBQKlipperThrottleState\fP & value)"

.SS "bool QKlipperThrottleState::operator== (\fBQKlipperThrottleState\fP && value)"

.SS "void QKlipperThrottleState::setBits (qint32 bits)\fC [slot]\fP"

.SS "void QKlipperThrottleState::setFlags (const QStringList & flags)\fC [slot]\fP"

.SH "Property Documentation"
.PP 
.SS "qint32 QKlipperThrottleState::bits\fC [read]\fP, \fC [write]\fP"

.SS "QStringList QKlipperThrottleState::flags\fC [read]\fP, \fC [write]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for QKlipper from the source code\&.
