.TH "QKlipperAdjustmentScrew::Adjustment" 3 "Version 0.2" "QKlipper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QKlipperAdjustmentScrew::Adjustment
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qklipperadjustmentscrew\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBDirection\fP { \fBClockwise\fP, \fBCounterClockwise\fP, \fBNotSet\fP = -1 }"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QString \fBamount\fP"
.br
.ti -1c
.RI "QString \fBsign\fP"
.br
.ti -1c
.RI "\fBDirection\fP \fBdirection\fP = \fBNotSet\fP"
.br
.ti -1c
.RI "bool \fBisBase\fP = false"
.br
.ti -1c
.RI "qreal \fBz\fP = 0"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBQKlipperAdjustmentScrew::Adjustment::Direction\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIClockwise \fP\fP
.TP
\fB\fICounterClockwise \fP\fP
.TP
\fB\fINotSet \fP\fP
.SH "Member Data Documentation"
.PP 
.SS "QString QKlipperAdjustmentScrew::Adjustment::amount"

.SS "\fBDirection\fP QKlipperAdjustmentScrew::Adjustment::direction = \fBNotSet\fP"

.SS "bool QKlipperAdjustmentScrew::Adjustment::isBase = false"

.SS "QString QKlipperAdjustmentScrew::Adjustment::sign"

.SS "qreal QKlipperAdjustmentScrew::Adjustment::z = 0"


.SH "Author"
.PP 
Generated automatically by Doxygen for QKlipper from the source code\&.
