.TH "QKlipperCanBusDevice" 3 "Version 0.2" "QKlipper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QKlipperCanBusDevice \- Filled by machine\&.system_info\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qklippercanbusdevice\&.h>\fP
.PP
Inherits QObject\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBsetQueueLength\fP (qint16 \fBqueueLength\fP)"
.br
.ti -1c
.RI "void \fBsetBitrate\fP (qint32 \fBbitrate\fP)"
.br
.ti -1c
.RI "void \fBsetDriver\fP (const QString &\fBdriver\fP)"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBqueueLengthChanged\fP ()"
.br
.ti -1c
.RI "void \fBbitrateChanged\fP ()"
.br
.ti -1c
.RI "void \fBdriverChanged\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQKlipperCanBusDevice\fP (QObject *parent=nullptr)"
.br
.ti -1c
.RI "\fBQKlipperCanBusDevice\fP (const \fBQKlipperCanBusDevice\fP &value)"
.br
.ti -1c
.RI "\fBQKlipperCanBusDevice\fP (\fBQKlipperCanBusDevice\fP &&value)"
.br
.ti -1c
.RI "\fBQKlipperCanBusDevice\fP & \fBoperator=\fP (const \fBQKlipperCanBusDevice\fP &value)"
.br
.ti -1c
.RI "\fBQKlipperCanBusDevice\fP & \fBoperator=\fP (\fBQKlipperCanBusDevice\fP &&value)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBQKlipperCanBusDevice\fP &value)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (\fBQKlipperCanBusDevice\fP &&value)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBQKlipperCanBusDevice\fP &value)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (\fBQKlipperCanBusDevice\fP &&value)"
.br
.ti -1c
.RI "qint16 \fBqueueLength\fP () const"
.br
.ti -1c
.RI "qint32 \fBbitrate\fP () const"
.br
.ti -1c
.RI "QString \fBdriver\fP () const"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "qint16 \fBqueueLength\fP"
.br
.ti -1c
.RI "qint32 \fBbitrate\fP"
.br
.ti -1c
.RI "QString \fBdriver\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Filled by machine\&.system_info\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QKlipperCanBusDevice::QKlipperCanBusDevice (QObject * parent = \fCnullptr\fP)\fC [explicit]\fP"

.SS "QKlipperCanBusDevice::QKlipperCanBusDevice (const \fBQKlipperCanBusDevice\fP & value)"

.SS "QKlipperCanBusDevice::QKlipperCanBusDevice (\fBQKlipperCanBusDevice\fP && value)"

.SH "Member Function Documentation"
.PP 
.SS "qint32 QKlipperCanBusDevice::bitrate () const"

.SS "void QKlipperCanBusDevice::bitrateChanged ()\fC [signal]\fP"

.SS "QString QKlipperCanBusDevice::driver () const"

.SS "void QKlipperCanBusDevice::driverChanged ()\fC [signal]\fP"

.SS "bool QKlipperCanBusDevice::operator!= (const \fBQKlipperCanBusDevice\fP & value)"

.SS "bool QKlipperCanBusDevice::operator!= (\fBQKlipperCanBusDevice\fP && value)"

.SS "\fBQKlipperCanBusDevice\fP & QKlipperCanBusDevice::operator= (const \fBQKlipperCanBusDevice\fP & value)"

.SS "\fBQKlipperCanBusDevice\fP & QKlipperCanBusDevice::operator= (\fBQKlipperCanBusDevice\fP && value)"

.SS "bool QKlipperCanBusDevice::operator== (const \fBQKlipperCanBusDevice\fP & value)"

.SS "bool QKlipperCanBusDevice::operator== (\fBQKlipperCanBusDevice\fP && value)"

.SS "qint16 QKlipperCanBusDevice::queueLength () const"

.SS "void QKlipperCanBusDevice::queueLengthChanged ()\fC [signal]\fP"

.SS "void QKlipperCanBusDevice::setBitrate (qint32 bitrate)\fC [slot]\fP"

.SS "void QKlipperCanBusDevice::setDriver (const QString & driver)\fC [slot]\fP"

.SS "void QKlipperCanBusDevice::setQueueLength (qint16 queueLength)\fC [slot]\fP"

.SH "Property Documentation"
.PP 
.SS "qint32 QKlipperCanBusDevice::bitrate\fC [read]\fP, \fC [write]\fP"

.SS "QString QKlipperCanBusDevice::driver\fC [read]\fP, \fC [write]\fP"

.SS "qint16 QKlipperCanBusDevice::queueLength\fC [read]\fP, \fC [write]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for QKlipper from the source code\&.
