.TH "/home/parametheus/repo/QKlipper/QKlipperServer/qklippergcodemacro.h" 3 "Version 0.2" "QKlipper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/parametheus/repo/QKlipper/QKlipperServer/qklippergcodemacro.h
.SH SYNOPSIS
.br
.PP
\fC#include <QObject>\fP
.br
\fC#include <QList>\fP
.br
\fC#include <QMap>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBQKlipperGCodeMacro\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef QList< \fBQKlipperGCodeMacro\fP > \fBQKlipperGCodeMacroList\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef QList<\fBQKlipperGCodeMacro\fP> \fBQKlipperGCodeMacroList\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for QKlipper from the source code\&.
