.TH "QKlipperCpuInfo" 3 "Version 0.2" "QKlipper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QKlipperCpuInfo \- Filled by machine\&.system_info\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qklippercpuinfo\&.h>\fP
.PP
Inherits QObject\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBcpuCountChanged\fP ()"
.br
.ti -1c
.RI "void \fBbitCountChanged\fP ()"
.br
.ti -1c
.RI "void \fBtotalMemoryChanged\fP ()"
.br
.ti -1c
.RI "void \fBtempChanged\fP ()"
.br
.ti -1c
.RI "void \fBusageChanged\fP ()"
.br
.ti -1c
.RI "void \fBprocessorChanged\fP ()"
.br
.ti -1c
.RI "void \fBdescriptionChanged\fP ()"
.br
.ti -1c
.RI "void \fBserialNumberChanged\fP ()"
.br
.ti -1c
.RI "void \fBhardwareDescriptionChanged\fP ()"
.br
.ti -1c
.RI "void \fBmodelChanged\fP ()"
.br
.ti -1c
.RI "void \fBmemoryUnitsChanged\fP ()"
.br
.ti -1c
.RI "void \fBcoreUsageChanged\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQKlipperCpuInfo\fP (QObject *parent=nullptr)"
.br
.ti -1c
.RI "\fBQKlipperCpuInfo\fP (const \fBQKlipperCpuInfo\fP &value)"
.br
.ti -1c
.RI "\fBQKlipperCpuInfo\fP (\fBQKlipperCpuInfo\fP &&value)"
.br
.ti -1c
.RI "\fBQKlipperCpuInfo\fP & \fBoperator=\fP (const \fBQKlipperCpuInfo\fP &value)"
.br
.ti -1c
.RI "\fBQKlipperCpuInfo\fP & \fBoperator=\fP (\fBQKlipperCpuInfo\fP &&value)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBQKlipperCpuInfo\fP &value)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (\fBQKlipperCpuInfo\fP &&value)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBQKlipperCpuInfo\fP &value)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (\fBQKlipperCpuInfo\fP &&value)"
.br
.ti -1c
.RI "qint32 \fBcpuCount\fP () const"
.br
.ti -1c
.RI "qint32 \fBbitCount\fP () const"
.br
.ti -1c
.RI "qint64 \fBtotalMemory\fP () const"
.br
.ti -1c
.RI "qreal \fBtemp\fP () const"
.br
.ti -1c
.RI "qreal \fBusage\fP () const"
.br
.ti -1c
.RI "QString \fBprocessor\fP () const"
.br
.ti -1c
.RI "QString \fBdescription\fP () const"
.br
.ti -1c
.RI "QString \fBserialNumber\fP () const"
.br
.ti -1c
.RI "QString \fBhardwareDescription\fP () const"
.br
.ti -1c
.RI "QString \fBmodel\fP () const"
.br
.ti -1c
.RI "QString \fBmemoryUnits\fP () const"
.br
.ti -1c
.RI "QList< qreal > \fBcoreUsage\fP () const"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "qint32 \fBcpuCount\fP"
.br
.ti -1c
.RI "qint32 \fBbitCount\fP"
.br
.ti -1c
.RI "qint64 \fBtotalMemory\fP"
.br
.ti -1c
.RI "qreal \fBtemp\fP"
.br
.ti -1c
.RI "qreal \fBusage\fP"
.br
.ti -1c
.RI "QString \fBprocessor\fP"
.br
.ti -1c
.RI "QString \fBdescription\fP"
.br
.ti -1c
.RI "QString \fBserialNumber\fP"
.br
.ti -1c
.RI "QString \fBhardwareDescription\fP"
.br
.ti -1c
.RI "QString \fBmodel\fP"
.br
.ti -1c
.RI "QString \fBmemoryUnits\fP"
.br
.ti -1c
.RI "QList< qreal > \fBcoreUsage\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Filled by machine\&.system_info\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QKlipperCpuInfo::QKlipperCpuInfo (QObject * parent = \fCnullptr\fP)\fC [explicit]\fP"

.SS "QKlipperCpuInfo::QKlipperCpuInfo (const \fBQKlipperCpuInfo\fP & value)"

.SS "QKlipperCpuInfo::QKlipperCpuInfo (\fBQKlipperCpuInfo\fP && value)"

.SH "Member Function Documentation"
.PP 
.SS "qint32 QKlipperCpuInfo::bitCount () const"

.SS "void QKlipperCpuInfo::bitCountChanged ()\fC [signal]\fP"

.SS "QList< qreal > QKlipperCpuInfo::coreUsage () const"

.SS "void QKlipperCpuInfo::coreUsageChanged ()\fC [signal]\fP"

.SS "qint32 QKlipperCpuInfo::cpuCount () const"

.SS "void QKlipperCpuInfo::cpuCountChanged ()\fC [signal]\fP"

.SS "QString QKlipperCpuInfo::description () const"

.SS "void QKlipperCpuInfo::descriptionChanged ()\fC [signal]\fP"

.SS "QString QKlipperCpuInfo::hardwareDescription () const"

.SS "void QKlipperCpuInfo::hardwareDescriptionChanged ()\fC [signal]\fP"

.SS "QString QKlipperCpuInfo::memoryUnits () const"

.SS "void QKlipperCpuInfo::memoryUnitsChanged ()\fC [signal]\fP"

.SS "QString QKlipperCpuInfo::model () const"

.SS "void QKlipperCpuInfo::modelChanged ()\fC [signal]\fP"

.SS "bool QKlipperCpuInfo::operator!= (const \fBQKlipperCpuInfo\fP & value)"

.SS "bool QKlipperCpuInfo::operator!= (\fBQKlipperCpuInfo\fP && value)"

.SS "\fBQKlipperCpuInfo\fP & QKlipperCpuInfo::operator= (const \fBQKlipperCpuInfo\fP & value)"

.SS "\fBQKlipperCpuInfo\fP & QKlipperCpuInfo::operator= (\fBQKlipperCpuInfo\fP && value)"

.SS "bool QKlipperCpuInfo::operator== (const \fBQKlipperCpuInfo\fP & value)"

.SS "bool QKlipperCpuInfo::operator== (\fBQKlipperCpuInfo\fP && value)"

.SS "QString QKlipperCpuInfo::processor () const"

.SS "void QKlipperCpuInfo::processorChanged ()\fC [signal]\fP"

.SS "QString QKlipperCpuInfo::serialNumber () const"

.SS "void QKlipperCpuInfo::serialNumberChanged ()\fC [signal]\fP"

.SS "qreal QKlipperCpuInfo::temp () const"

.SS "void QKlipperCpuInfo::tempChanged ()\fC [signal]\fP"

.SS "qint64 QKlipperCpuInfo::totalMemory () const"

.SS "void QKlipperCpuInfo::totalMemoryChanged ()\fC [signal]\fP"

.SS "qreal QKlipperCpuInfo::usage () const"

.SS "void QKlipperCpuInfo::usageChanged ()\fC [signal]\fP"

.SH "Property Documentation"
.PP 
.SS "qint32 QKlipperCpuInfo::bitCount\fC [read]\fP, \fC [write]\fP"

.SS "QList<qreal> QKlipperCpuInfo::coreUsage\fC [read]\fP, \fC [write]\fP"

.SS "qint32 QKlipperCpuInfo::cpuCount\fC [read]\fP, \fC [write]\fP"

.SS "QString QKlipperCpuInfo::description\fC [read]\fP, \fC [write]\fP"

.SS "QString QKlipperCpuInfo::hardwareDescription\fC [read]\fP, \fC [write]\fP"

.SS "QString QKlipperCpuInfo::memoryUnits\fC [read]\fP, \fC [write]\fP"

.SS "QString QKlipperCpuInfo::model\fC [read]\fP, \fC [write]\fP"

.SS "QString QKlipperCpuInfo::processor\fC [read]\fP, \fC [write]\fP"

.SS "QString QKlipperCpuInfo::serialNumber\fC [read]\fP, \fC [write]\fP"

.SS "qreal QKlipperCpuInfo::temp\fC [read]\fP, \fC [write]\fP"

.SS "qint64 QKlipperCpuInfo::totalMemory\fC [read]\fP, \fC [write]\fP"

.SS "qreal QKlipperCpuInfo::usage\fC [read]\fP, \fC [write]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for QKlipper from the source code\&.
