.TH "QKlipperV412Device" 3 "Version 0.2" "QKlipper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QKlipperV412Device
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qklipperv412device\&.h>\fP
.PP
Inherits QObject\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBsetName\fP (const QString &\fBname\fP)"
.br
.ti -1c
.RI "void \fBsetPath\fP (const QString &\fBpath\fP)"
.br
.ti -1c
.RI "void \fBsetCameraName\fP (const QString &\fBcameraName\fP)"
.br
.ti -1c
.RI "void \fBsetDriver\fP (const QString &\fBdriver\fP)"
.br
.ti -1c
.RI "void \fBsetAltName\fP (const QString &\fBaltName\fP)"
.br
.ti -1c
.RI "void \fBsetHardwareBus\fP (const QString &\fBhardwareBus\fP)"
.br
.ti -1c
.RI "void \fBsetVersion\fP (const QString &\fBversion\fP)"
.br
.ti -1c
.RI "void \fBsetHardwarePath\fP (const QString &\fBhardwarePath\fP)"
.br
.ti -1c
.RI "void \fBsetPathById\fP (const QString &\fBpathById\fP)"
.br
.ti -1c
.RI "void \fBsetUsbLocation\fP (const QString &\fBusbLocation\fP)"
.br
.ti -1c
.RI "void \fBsetCapabilities\fP (const QStringList &\fBcapabilities\fP)"
.br
.ti -1c
.RI "void \fBsetModes\fP (const QList< \fBQKlipperV412Mode\fP > &\fBmodes\fP)"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBnameChanged\fP ()"
.br
.ti -1c
.RI "void \fBpathChanged\fP ()"
.br
.ti -1c
.RI "void \fBcameraNameChanged\fP ()"
.br
.ti -1c
.RI "void \fBdriverChanged\fP ()"
.br
.ti -1c
.RI "void \fBaltNameChanged\fP ()"
.br
.ti -1c
.RI "void \fBhardwareBusChanged\fP ()"
.br
.ti -1c
.RI "void \fBversionChanged\fP ()"
.br
.ti -1c
.RI "void \fBhardwarePathChanged\fP ()"
.br
.ti -1c
.RI "void \fBpathByIdChanged\fP ()"
.br
.ti -1c
.RI "void \fBusbLocationChanged\fP ()"
.br
.ti -1c
.RI "void \fBcapabilitiesChanged\fP ()"
.br
.ti -1c
.RI "void \fBmodesChanged\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQKlipperV412Device\fP (QObject *parent=nullptr)"
.br
.ti -1c
.RI "\fBQKlipperV412Device\fP (const \fBQKlipperV412Device\fP &value)"
.br
.ti -1c
.RI "\fBQKlipperV412Device\fP (\fBQKlipperV412Device\fP &&value)"
.br
.ti -1c
.RI "\fBQKlipperV412Device\fP & \fBoperator=\fP (const \fBQKlipperV412Device\fP &value)"
.br
.ti -1c
.RI "\fBQKlipperV412Device\fP & \fBoperator=\fP (\fBQKlipperV412Device\fP &&value)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBQKlipperV412Device\fP &value)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (\fBQKlipperV412Device\fP &&value)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBQKlipperV412Device\fP &value)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (\fBQKlipperV412Device\fP &&value)"
.br
.ti -1c
.RI "QString \fBname\fP () const"
.br
.ti -1c
.RI "QString \fBpath\fP () const"
.br
.ti -1c
.RI "QString \fBcameraName\fP () const"
.br
.ti -1c
.RI "QString \fBdriver\fP () const"
.br
.ti -1c
.RI "QString \fBaltName\fP () const"
.br
.ti -1c
.RI "QString \fBhardwareBus\fP () const"
.br
.ti -1c
.RI "QString \fBversion\fP () const"
.br
.ti -1c
.RI "QString \fBhardwarePath\fP () const"
.br
.ti -1c
.RI "QString \fBpathById\fP () const"
.br
.ti -1c
.RI "QString \fBusbLocation\fP () const"
.br
.ti -1c
.RI "QStringList \fBcapabilities\fP () const"
.br
.ti -1c
.RI "QList< \fBQKlipperV412Mode\fP > \fBmodes\fP () const"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "QString \fBname\fP"
.br
.ti -1c
.RI "QString \fBpath\fP"
.br
.ti -1c
.RI "QString \fBcameraName\fP"
.br
.ti -1c
.RI "QString \fBdriver\fP"
.br
.ti -1c
.RI "QString \fBaltName\fP"
.br
.ti -1c
.RI "QString \fBhardwareBus\fP"
.br
.ti -1c
.RI "QString \fBversion\fP"
.br
.ti -1c
.RI "QString \fBhardwarePath\fP"
.br
.ti -1c
.RI "QString \fBpathById\fP"
.br
.ti -1c
.RI "QString \fBusbLocation\fP"
.br
.ti -1c
.RI "QStringList \fBcapabilities\fP"
.br
.ti -1c
.RI "QList< \fBQKlipperV412Mode\fP > \fBmodes\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QKlipperV412Device::QKlipperV412Device (QObject * parent = \fCnullptr\fP)\fC [explicit]\fP"

.SS "QKlipperV412Device::QKlipperV412Device (const \fBQKlipperV412Device\fP & value)"

.SS "QKlipperV412Device::QKlipperV412Device (\fBQKlipperV412Device\fP && value)"

.SH "Member Function Documentation"
.PP 
.SS "QString QKlipperV412Device::altName () const"

.SS "void QKlipperV412Device::altNameChanged ()\fC [signal]\fP"

.SS "QString QKlipperV412Device::cameraName () const"

.SS "void QKlipperV412Device::cameraNameChanged ()\fC [signal]\fP"

.SS "QStringList QKlipperV412Device::capabilities () const"

.SS "void QKlipperV412Device::capabilitiesChanged ()\fC [signal]\fP"

.SS "QString QKlipperV412Device::driver () const"

.SS "void QKlipperV412Device::driverChanged ()\fC [signal]\fP"

.SS "QString QKlipperV412Device::hardwareBus () const"

.SS "void QKlipperV412Device::hardwareBusChanged ()\fC [signal]\fP"

.SS "QString QKlipperV412Device::hardwarePath () const"

.SS "void QKlipperV412Device::hardwarePathChanged ()\fC [signal]\fP"

.SS "QList< \fBQKlipperV412Mode\fP > QKlipperV412Device::modes () const"

.SS "void QKlipperV412Device::modesChanged ()\fC [signal]\fP"

.SS "QString QKlipperV412Device::name () const"

.SS "void QKlipperV412Device::nameChanged ()\fC [signal]\fP"

.SS "bool QKlipperV412Device::operator!= (const \fBQKlipperV412Device\fP & value)"

.SS "bool QKlipperV412Device::operator!= (\fBQKlipperV412Device\fP && value)"

.SS "\fBQKlipperV412Device\fP & QKlipperV412Device::operator= (const \fBQKlipperV412Device\fP & value)"

.SS "\fBQKlipperV412Device\fP & QKlipperV412Device::operator= (\fBQKlipperV412Device\fP && value)"

.SS "bool QKlipperV412Device::operator== (const \fBQKlipperV412Device\fP & value)"

.SS "bool QKlipperV412Device::operator== (\fBQKlipperV412Device\fP && value)"

.SS "QString QKlipperV412Device::path () const"

.SS "QString QKlipperV412Device::pathById () const"

.SS "void QKlipperV412Device::pathByIdChanged ()\fC [signal]\fP"

.SS "void QKlipperV412Device::pathChanged ()\fC [signal]\fP"

.SS "void QKlipperV412Device::setAltName (const QString & altName)\fC [slot]\fP"

.SS "void QKlipperV412Device::setCameraName (const QString & cameraName)\fC [slot]\fP"

.SS "void QKlipperV412Device::setCapabilities (const QStringList & capabilities)\fC [slot]\fP"

.SS "void QKlipperV412Device::setDriver (const QString & driver)\fC [slot]\fP"

.SS "void QKlipperV412Device::setHardwareBus (const QString & hardwareBus)\fC [slot]\fP"

.SS "void QKlipperV412Device::setHardwarePath (const QString & hardwarePath)\fC [slot]\fP"

.SS "void QKlipperV412Device::setModes (const QList< \fBQKlipperV412Mode\fP > & modes)\fC [slot]\fP"

.SS "void QKlipperV412Device::setName (const QString & name)\fC [slot]\fP"

.SS "void QKlipperV412Device::setPath (const QString & path)\fC [slot]\fP"

.SS "void QKlipperV412Device::setPathById (const QString & pathById)\fC [slot]\fP"

.SS "void QKlipperV412Device::setUsbLocation (const QString & usbLocation)\fC [slot]\fP"

.SS "void QKlipperV412Device::setVersion (const QString & version)\fC [slot]\fP"

.SS "QString QKlipperV412Device::usbLocation () const"

.SS "void QKlipperV412Device::usbLocationChanged ()\fC [signal]\fP"

.SS "QString QKlipperV412Device::version () const"

.SS "void QKlipperV412Device::versionChanged ()\fC [signal]\fP"

.SH "Property Documentation"
.PP 
.SS "QString QKlipperV412Device::altName\fC [read]\fP, \fC [write]\fP"

.SS "QString QKlipperV412Device::cameraName\fC [read]\fP, \fC [write]\fP"

.SS "QStringList QKlipperV412Device::capabilities\fC [read]\fP, \fC [write]\fP"

.SS "QString QKlipperV412Device::driver\fC [read]\fP, \fC [write]\fP"

.SS "QString QKlipperV412Device::hardwareBus\fC [read]\fP, \fC [write]\fP"

.SS "QString QKlipperV412Device::hardwarePath\fC [read]\fP, \fC [write]\fP"

.SS "QList<\fBQKlipperV412Mode\fP> QKlipperV412Device::modes\fC [read]\fP, \fC [write]\fP"

.SS "QString QKlipperV412Device::name\fC [read]\fP, \fC [write]\fP"

.SS "QString QKlipperV412Device::path\fC [read]\fP, \fC [write]\fP"

.SS "QString QKlipperV412Device::pathById\fC [read]\fP, \fC [write]\fP"

.SS "QString QKlipperV412Device::usbLocation\fC [read]\fP, \fC [write]\fP"

.SS "QString QKlipperV412Device::version\fC [read]\fP, \fC [write]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for QKlipper from the source code\&.
