.TH "QKlipperGCodeMacro" 3 "Version 0.2" "QKlipper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QKlipperGCodeMacro
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qklippergcodemacro\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBcontains\fP (const QString &key)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBQKlipperGCodeMacro\fP &value)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (\fBQKlipperGCodeMacro\fP &&value)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBQKlipperGCodeMacro\fP &value)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (\fBQKlipperGCodeMacro\fP &&value)"
.br
.ti -1c
.RI "QString & \fBoperator[]\fP (const QString &key)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QString \fBmacro\fP"
.br
.ti -1c
.RI "QString \fBdescription\fP"
.br
.ti -1c
.RI "QString \fBgcode\fP"
.br
.ti -1c
.RI "QString \fBreplaces\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bool QKlipperGCodeMacro::contains (const QString & key)\fC [inline]\fP"

.SS "bool QKlipperGCodeMacro::operator!= (const \fBQKlipperGCodeMacro\fP & value)\fC [inline]\fP"

.SS "bool QKlipperGCodeMacro::operator!= (\fBQKlipperGCodeMacro\fP && value)\fC [inline]\fP"

.SS "bool QKlipperGCodeMacro::operator== (const \fBQKlipperGCodeMacro\fP & value)\fC [inline]\fP"

.SS "bool QKlipperGCodeMacro::operator== (\fBQKlipperGCodeMacro\fP && value)\fC [inline]\fP"

.SS "QString & QKlipperGCodeMacro::operator[] (const QString & key)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "QString QKlipperGCodeMacro::description"

.SS "QString QKlipperGCodeMacro::gcode"

.SS "QString QKlipperGCodeMacro::macro"

.SS "QString QKlipperGCodeMacro::replaces"


.SH "Author"
.PP 
Generated automatically by Doxygen for QKlipper from the source code\&.
