.TH "QKlipperGCodeMove" 3 "Version 0.2" "QKlipper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QKlipperGCodeMove
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qklippergcodemove\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBQKlipperGCodeMove\fP &move)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBQKlipperGCodeMove\fP &move)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBabsoluteCoordinates\fP = false"
.br
.ti -1c
.RI "bool \fBabsoluteExtrude\fP = false"
.br
.ti -1c
.RI "qreal \fBextrusionFactor\fP = 0"
.br
.ti -1c
.RI "qreal \fBspeedFactor\fP = 0"
.br
.ti -1c
.RI "qreal \fBspeed\fP = 0"
.br
.ti -1c
.RI "\fBQKlipperPosition\fP \fBgcodePosition\fP"
.br
.ti -1c
.RI "\fBQKlipperPosition\fP \fBhomingOrigin\fP"
.br
.ti -1c
.RI "\fBQKlipperPosition\fP \fBposition\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bool QKlipperGCodeMove::operator!= (const \fBQKlipperGCodeMove\fP & move)\fC [inline]\fP"

.SS "bool QKlipperGCodeMove::operator== (const \fBQKlipperGCodeMove\fP & move)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "bool QKlipperGCodeMove::absoluteCoordinates = false"

.SS "bool QKlipperGCodeMove::absoluteExtrude = false"

.SS "qreal QKlipperGCodeMove::extrusionFactor = 0"

.SS "\fBQKlipperPosition\fP QKlipperGCodeMove::gcodePosition"

.SS "\fBQKlipperPosition\fP QKlipperGCodeMove::homingOrigin"

.SS "\fBQKlipperPosition\fP QKlipperGCodeMove::position"

.SS "qreal QKlipperGCodeMove::speed = 0"

.SS "qreal QKlipperGCodeMove::speedFactor = 0"


.SH "Author"
.PP 
Generated automatically by Doxygen for QKlipper from the source code\&.
