.TH "QKlipperAccessDetails" 3 "Version 0.2" "QKlipper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QKlipperAccessDetails
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qklipperaccessdetails\&.h>\fP
.PP
Inherits QObject\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBsetIsLoggedIn\fP (bool \fBisLoggedIn\fP)"
.br
.ti -1c
.RI "void \fBsetToken\fP (const QString &\fBtoken\fP)"
.br
.ti -1c
.RI "void \fBsetRefreshToken\fP (const QString &\fBrefreshToken\fP)"
.br
.ti -1c
.RI "void \fBsetUser\fP (const \fBQKlipperUser\fP &\fBuser\fP)"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBisLoggedInChanged\fP ()"
.br
.ti -1c
.RI "void \fBtokenChanged\fP ()"
.br
.ti -1c
.RI "void \fBrefreshTokenChanged\fP ()"
.br
.ti -1c
.RI "void \fBuserChanged\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQKlipperAccessDetails\fP (QObject *parent=nullptr)"
.br
.ti -1c
.RI "\fB~QKlipperAccessDetails\fP ()"
.br
.ti -1c
.RI "\fBQKlipperAccessDetails\fP (const \fBQKlipperAccessDetails\fP &value)"
.br
.ti -1c
.RI "\fBQKlipperAccessDetails\fP (\fBQKlipperAccessDetails\fP &&value)"
.br
.ti -1c
.RI "\fBQKlipperAccessDetails\fP & \fBoperator=\fP (const \fBQKlipperAccessDetails\fP &value)"
.br
.ti -1c
.RI "\fBQKlipperAccessDetails\fP & \fBoperator=\fP (\fBQKlipperAccessDetails\fP &&value)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBQKlipperAccessDetails\fP &value)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (\fBQKlipperAccessDetails\fP &&value)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBQKlipperAccessDetails\fP &value)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (\fBQKlipperAccessDetails\fP &&value)"
.br
.ti -1c
.RI "bool \fBisLoggedIn\fP () const"
.br
.ti -1c
.RI "QString \fBtoken\fP () const"
.br
.ti -1c
.RI "QString \fBrefreshToken\fP () const"
.br
.ti -1c
.RI "\fBQKlipperUser\fP \fBuser\fP () const"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBisLoggedIn\fP"
.br
.ti -1c
.RI "QString \fBtoken\fP"
.br
.ti -1c
.RI "QString \fBrefreshToken\fP"
.br
.ti -1c
.RI "\fBQKlipperUser\fP \fBuser\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QKlipperAccessDetails::QKlipperAccessDetails (QObject * parent = \fCnullptr\fP)\fC [explicit]\fP"

.SS "QKlipperAccessDetails::~QKlipperAccessDetails ()"

.SS "QKlipperAccessDetails::QKlipperAccessDetails (const \fBQKlipperAccessDetails\fP & value)"

.SS "QKlipperAccessDetails::QKlipperAccessDetails (\fBQKlipperAccessDetails\fP && value)"

.SH "Member Function Documentation"
.PP 
.SS "bool QKlipperAccessDetails::isLoggedIn () const"

.SS "void QKlipperAccessDetails::isLoggedInChanged ()\fC [signal]\fP"

.SS "bool QKlipperAccessDetails::operator!= (const \fBQKlipperAccessDetails\fP & value)"

.SS "bool QKlipperAccessDetails::operator!= (\fBQKlipperAccessDetails\fP && value)"

.SS "\fBQKlipperAccessDetails\fP & QKlipperAccessDetails::operator= (const \fBQKlipperAccessDetails\fP & value)"

.SS "\fBQKlipperAccessDetails\fP & QKlipperAccessDetails::operator= (\fBQKlipperAccessDetails\fP && value)"

.SS "bool QKlipperAccessDetails::operator== (const \fBQKlipperAccessDetails\fP & value)"

.SS "bool QKlipperAccessDetails::operator== (\fBQKlipperAccessDetails\fP && value)"

.SS "QString QKlipperAccessDetails::refreshToken () const"

.SS "void QKlipperAccessDetails::refreshTokenChanged ()\fC [signal]\fP"

.SS "void QKlipperAccessDetails::setIsLoggedIn (bool isLoggedIn)\fC [slot]\fP"

.SS "void QKlipperAccessDetails::setRefreshToken (const QString & refreshToken)\fC [slot]\fP"

.SS "void QKlipperAccessDetails::setToken (const QString & token)\fC [slot]\fP"

.SS "void QKlipperAccessDetails::setUser (const \fBQKlipperUser\fP & user)\fC [slot]\fP"

.SS "QString QKlipperAccessDetails::token () const"

.SS "void QKlipperAccessDetails::tokenChanged ()\fC [signal]\fP"

.SS "\fBQKlipperUser\fP QKlipperAccessDetails::user () const"

.SS "void QKlipperAccessDetails::userChanged ()\fC [signal]\fP"

.SH "Property Documentation"
.PP 
.SS "bool QKlipperAccessDetails::isLoggedIn\fC [read]\fP, \fC [write]\fP"

.SS "QString QKlipperAccessDetails::refreshToken\fC [read]\fP, \fC [write]\fP"

.SS "QString QKlipperAccessDetails::token\fC [read]\fP, \fC [write]\fP"

.SS "\fBQKlipperUser\fP QKlipperAccessDetails::user\fC [read]\fP, \fC [write]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for QKlipper from the source code\&.
