.TH "QKlipperNetworkInterface" 3 "Version 0.2" "QKlipper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QKlipperNetworkInterface \- Filled by machine\&.system_info\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qklippernetworkinterface\&.h>\fP
.PP
Inherits QObject\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBsetMacAddress\fP (const QString &\fBmacAddress\fP)"
.br
.ti -1c
.RI "void \fBsetIpAddresses\fP (const QList< \fBQKlipperNetworkAddress\fP > &\fBipAddresses\fP)"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBmacAddressChanged\fP ()"
.br
.ti -1c
.RI "void \fBipAddressesChanged\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQKlipperNetworkInterface\fP (QObject *parent=nullptr)"
.br
.ti -1c
.RI "\fBQKlipperNetworkInterface\fP (const \fBQKlipperNetworkInterface\fP &value)"
.br
.ti -1c
.RI "\fBQKlipperNetworkInterface\fP (\fBQKlipperNetworkInterface\fP &&value)"
.br
.ti -1c
.RI "\fBQKlipperNetworkInterface\fP & \fBoperator=\fP (const \fBQKlipperNetworkInterface\fP &value)"
.br
.ti -1c
.RI "\fBQKlipperNetworkInterface\fP & \fBoperator=\fP (\fBQKlipperNetworkInterface\fP &&value)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBQKlipperNetworkInterface\fP &value)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (\fBQKlipperNetworkInterface\fP &&value)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBQKlipperNetworkInterface\fP &value)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (\fBQKlipperNetworkInterface\fP &&value)"
.br
.ti -1c
.RI "QString \fBmacAddress\fP () const"
.br
.ti -1c
.RI "QList< \fBQKlipperNetworkAddress\fP > \fBipAddresses\fP () const"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "QString \fBmacAddress\fP"
.br
.ti -1c
.RI "QList< \fBQKlipperNetworkAddress\fP > \fBipAddresses\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Filled by machine\&.system_info\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QKlipperNetworkInterface::QKlipperNetworkInterface (QObject * parent = \fCnullptr\fP)\fC [explicit]\fP"

.SS "QKlipperNetworkInterface::QKlipperNetworkInterface (const \fBQKlipperNetworkInterface\fP & value)"

.SS "QKlipperNetworkInterface::QKlipperNetworkInterface (\fBQKlipperNetworkInterface\fP && value)"

.SH "Member Function Documentation"
.PP 
.SS "QList< \fBQKlipperNetworkAddress\fP > QKlipperNetworkInterface::ipAddresses () const"

.SS "void QKlipperNetworkInterface::ipAddressesChanged ()\fC [signal]\fP"

.SS "QString QKlipperNetworkInterface::macAddress () const"

.SS "void QKlipperNetworkInterface::macAddressChanged ()\fC [signal]\fP"

.SS "bool QKlipperNetworkInterface::operator!= (const \fBQKlipperNetworkInterface\fP & value)"

.SS "bool QKlipperNetworkInterface::operator!= (\fBQKlipperNetworkInterface\fP && value)"

.SS "\fBQKlipperNetworkInterface\fP & QKlipperNetworkInterface::operator= (const \fBQKlipperNetworkInterface\fP & value)"

.SS "\fBQKlipperNetworkInterface\fP & QKlipperNetworkInterface::operator= (\fBQKlipperNetworkInterface\fP && value)"

.SS "bool QKlipperNetworkInterface::operator== (const \fBQKlipperNetworkInterface\fP & value)"

.SS "bool QKlipperNetworkInterface::operator== (\fBQKlipperNetworkInterface\fP && value)"

.SS "void QKlipperNetworkInterface::setIpAddresses (const QList< \fBQKlipperNetworkAddress\fP > & ipAddresses)\fC [slot]\fP"

.SS "void QKlipperNetworkInterface::setMacAddress (const QString & macAddress)\fC [slot]\fP"

.SH "Property Documentation"
.PP 
.SS "QList<\fBQKlipperNetworkAddress\fP> QKlipperNetworkInterface::ipAddresses\fC [read]\fP, \fC [write]\fP"

.SS "QString QKlipperNetworkInterface::macAddress\fC [read]\fP, \fC [write]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for QKlipper from the source code\&.
