.TH "/home/parametheus/repo/QKlipper/QKlipperFile/qklipperfile.cpp" 3 "Version 0.2" "QKlipper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/parametheus/repo/QKlipper/QKlipperFile/qklipperfile.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'qklipperfile\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for QKlipper from the source code\&.
