.TH "QKlipperPosition" 3 "Version 0.2" "QKlipper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QKlipperPosition \- \fBQKlipperPosition\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qklipperposition\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "qreal & \fBoperator[]\fP (const QString &name)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBQKlipperPosition\fP &value)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (\fBQKlipperPosition\fP &&value)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBQKlipperPosition\fP &value)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (\fBQKlipperPosition\fP &&value)"
.br
.ti -1c
.RI "qreal \fBx\fP () const"
.br
.ti -1c
.RI "qreal \fBy\fP () const"
.br
.ti -1c
.RI "qreal \fBz\fP () const"
.br
.ti -1c
.RI "qreal \fBe\fP () const"
.br
.ti -1c
.RI "qreal \fBposition\fP (const QString &name) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBQKlipperPosition\fP class\&. 

This class holds data on the XYZ position as well as extruders\&. For extruders other than 'extruder0', use the position('e#') method 
.SH "Member Function Documentation"
.PP 
.SS "qreal QKlipperPosition::e () const"

.SS "bool QKlipperPosition::operator!= (const \fBQKlipperPosition\fP & value)"

.SS "bool QKlipperPosition::operator!= (\fBQKlipperPosition\fP && value)"

.SS "bool QKlipperPosition::operator== (const \fBQKlipperPosition\fP & value)"

.SS "bool QKlipperPosition::operator== (\fBQKlipperPosition\fP && value)"

.SS "qreal & QKlipperPosition::operator[] (const QString & name)"

.SS "qreal QKlipperPosition::position (const QString & name) const"

.SS "qreal QKlipperPosition::x () const"

.SS "qreal QKlipperPosition::y () const"

.SS "qreal QKlipperPosition::z () const"


.SH "Author"
.PP 
Generated automatically by Doxygen for QKlipper from the source code\&.
