.TH "QKlipperGCodeStoreValue" 3 "Version 0.2" "QKlipper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QKlipperGCodeStoreValue
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qklippergcodestorevalue\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBGCodeType\fP { \fBCommand\fP, \fBResponse\fP }"
.br
.in -1c
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBsetMessage\fP (const QString &\fBmessage\fP)"
.br
.ti -1c
.RI "void \fBsetGcodeType\fP (\fBGCodeType\fP \fBgcodeType\fP)"
.br
.ti -1c
.RI "void \fBsetTime\fP (qreal \fBtime\fP)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBQKlipperGCodeStoreValue\fP &value)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (\fBQKlipperGCodeStoreValue\fP &&value)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBQKlipperGCodeStoreValue\fP &value)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (\fBQKlipperGCodeStoreValue\fP &&value)"
.br
.ti -1c
.RI "QString \fBmessage\fP () const"
.br
.ti -1c
.RI "\fBGCodeType\fP \fBgcodeType\fP () const"
.br
.ti -1c
.RI "qreal \fBtime\fP () const"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBQKlipperGCodeStoreValue::GCodeType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fICommand \fP\fP
.TP
\fB\fIResponse \fP\fP
.SH "Member Function Documentation"
.PP 
.SS "\fBQKlipperGCodeStoreValue::GCodeType\fP QKlipperGCodeStoreValue::gcodeType () const"

.SS "QString QKlipperGCodeStoreValue::message () const"

.SS "bool QKlipperGCodeStoreValue::operator!= (const \fBQKlipperGCodeStoreValue\fP & value)"

.SS "bool QKlipperGCodeStoreValue::operator!= (\fBQKlipperGCodeStoreValue\fP && value)"

.SS "bool QKlipperGCodeStoreValue::operator== (const \fBQKlipperGCodeStoreValue\fP & value)"

.SS "bool QKlipperGCodeStoreValue::operator== (\fBQKlipperGCodeStoreValue\fP && value)"

.SS "void QKlipperGCodeStoreValue::setGcodeType (\fBGCodeType\fP gcodeType)\fC [slot]\fP"

.SS "void QKlipperGCodeStoreValue::setMessage (const QString & message)\fC [slot]\fP"

.SS "void QKlipperGCodeStoreValue::setTime (qreal time)\fC [slot]\fP"

.SS "qreal QKlipperGCodeStoreValue::time () const"


.SH "Author"
.PP 
Generated automatically by Doxygen for QKlipper from the source code\&.
