.TH "/home/parametheus/repo/QKlipper/QKlipperPrinter/qklipperextruder.h" 3 "Version 0.2" "QKlipper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/parametheus/repo/QKlipper/QKlipperPrinter/qklipperextruder.h
.SH SYNOPSIS
.br
.PP
\fC#include <QObject>\fP
.br
\fC#include <QList>\fP
.br
\fC#include 'qklipperposition\&.h'\fP
.br
\fC#include 'qklipperfan\&.h'\fP
.br
\fC#include 'qklippertemperaturestore\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBQKlipperExtruder\fP"
.br
.RI "\fBQKlipperExtruder\fP class\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef QPair< qint32, qint32 > \fBQKlipperGearRatio\fP"
.br
.RI "QKlipper - A Qt library for the Klipper/Moonraker API Copyright (C) 2024 James Dudeck\&. "
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef QPair<qint32,qint32> \fBQKlipperGearRatio\fP"

.PP
QKlipper - A Qt library for the Klipper/Moonraker API Copyright (C) 2024 James Dudeck\&. This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version\&.
.PP
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the GNU General Public License for more details\&.
.PP
You should have received a copy of the GNU General Public License along with this program\&. If not, see http://www.gnu.org/licenses/\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for QKlipper from the source code\&.
