.TH "QKlipperSdInfo" 3 "Version 0.2" "QKlipper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QKlipperSdInfo \- Filled by machine\&.system_info\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qklippersdinfo\&.h>\fP
.PP
Inherits QObject\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBsetTotalBytes\fP (qint64 \fBtotalBytes\fP)"
.br
.ti -1c
.RI "void \fBsetUsedBytes\fP (qint64 \fBusedBytes\fP)"
.br
.ti -1c
.RI "void \fBsetAvailableBytes\fP (qint64 \fBavailableBytes\fP)"
.br
.ti -1c
.RI "void \fBsetManufacturerId\fP (const QString &\fBmanufacturerId\fP)"
.br
.ti -1c
.RI "void \fBsetManufacturer\fP (const QString &\fBmanufacturer\fP)"
.br
.ti -1c
.RI "void \fBsetOemId\fP (const QString &\fBoemId\fP)"
.br
.ti -1c
.RI "void \fBsetProductName\fP (const QString &\fBproductName\fP)"
.br
.ti -1c
.RI "void \fBsetProductRevision\fP (const QString &\fBproductRevision\fP)"
.br
.ti -1c
.RI "void \fBsetSerialNumber\fP (const QString &\fBserialNumber\fP)"
.br
.ti -1c
.RI "void \fBsetManufacturerDate\fP (const QString &\fBmanufacturerDate\fP)"
.br
.ti -1c
.RI "void \fBsetCapacityString\fP (const QString &\fBcapacityString\fP)"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBtotalBytesChanged\fP ()"
.br
.ti -1c
.RI "void \fBusedBytesChanged\fP ()"
.br
.ti -1c
.RI "void \fBavailableBytesChanged\fP ()"
.br
.ti -1c
.RI "void \fBmanufacturerIdChanged\fP ()"
.br
.ti -1c
.RI "void \fBmanufacturerChanged\fP ()"
.br
.ti -1c
.RI "void \fBoemIdChanged\fP ()"
.br
.ti -1c
.RI "void \fBproductNameChanged\fP ()"
.br
.ti -1c
.RI "void \fBproductRevisionChanged\fP ()"
.br
.ti -1c
.RI "void \fBserialNumberChanged\fP ()"
.br
.ti -1c
.RI "void \fBmanufacturerDateChanged\fP ()"
.br
.ti -1c
.RI "void \fBcapacityStringChanged\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQKlipperSdInfo\fP (QObject *parent=nullptr)"
.br
.ti -1c
.RI "\fBQKlipperSdInfo\fP (const \fBQKlipperSdInfo\fP &value)"
.br
.ti -1c
.RI "\fBQKlipperSdInfo\fP (\fBQKlipperSdInfo\fP &&value)"
.br
.ti -1c
.RI "\fBQKlipperSdInfo\fP & \fBoperator=\fP (const \fBQKlipperSdInfo\fP &value)"
.br
.ti -1c
.RI "\fBQKlipperSdInfo\fP & \fBoperator=\fP (\fBQKlipperSdInfo\fP &&value)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBQKlipperSdInfo\fP &value)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (\fBQKlipperSdInfo\fP &&value)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBQKlipperSdInfo\fP &value)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (\fBQKlipperSdInfo\fP &&value)"
.br
.ti -1c
.RI "qint64 \fBtotalBytes\fP () const"
.br
.ti -1c
.RI "qint64 \fBusedBytes\fP () const"
.br
.ti -1c
.RI "qint64 \fBavailableBytes\fP () const"
.br
.ti -1c
.RI "QString \fBmanufacturerId\fP () const"
.br
.ti -1c
.RI "QString \fBmanufacturer\fP () const"
.br
.ti -1c
.RI "QString \fBoemId\fP () const"
.br
.ti -1c
.RI "QString \fBproductName\fP () const"
.br
.ti -1c
.RI "QString \fBproductRevision\fP () const"
.br
.ti -1c
.RI "QString \fBserialNumber\fP () const"
.br
.ti -1c
.RI "QString \fBmanufacturerDate\fP () const"
.br
.ti -1c
.RI "QString \fBcapacityString\fP () const"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "qint64 \fBtotalBytes\fP"
.br
.ti -1c
.RI "qint64 \fBusedBytes\fP"
.br
.ti -1c
.RI "qint64 \fBavailableBytes\fP"
.br
.ti -1c
.RI "QString \fBmanufacturerId\fP"
.br
.ti -1c
.RI "QString \fBmanufacturer\fP"
.br
.ti -1c
.RI "QString \fBoemId\fP"
.br
.ti -1c
.RI "QString \fBproductName\fP"
.br
.ti -1c
.RI "QString \fBproductRevision\fP"
.br
.ti -1c
.RI "QString \fBserialNumber\fP"
.br
.ti -1c
.RI "QString \fBmanufacturerDate\fP"
.br
.ti -1c
.RI "QString \fBcapacityString\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Filled by machine\&.system_info\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QKlipperSdInfo::QKlipperSdInfo (QObject * parent = \fCnullptr\fP)\fC [explicit]\fP"

.SS "QKlipperSdInfo::QKlipperSdInfo (const \fBQKlipperSdInfo\fP & value)"

.SS "QKlipperSdInfo::QKlipperSdInfo (\fBQKlipperSdInfo\fP && value)"

.SH "Member Function Documentation"
.PP 
.SS "qint64 QKlipperSdInfo::availableBytes () const"

.SS "void QKlipperSdInfo::availableBytesChanged ()\fC [signal]\fP"

.SS "QString QKlipperSdInfo::capacityString () const"

.SS "void QKlipperSdInfo::capacityStringChanged ()\fC [signal]\fP"

.SS "QString QKlipperSdInfo::manufacturer () const"

.SS "void QKlipperSdInfo::manufacturerChanged ()\fC [signal]\fP"

.SS "QString QKlipperSdInfo::manufacturerDate () const"

.SS "void QKlipperSdInfo::manufacturerDateChanged ()\fC [signal]\fP"

.SS "QString QKlipperSdInfo::manufacturerId () const"

.SS "void QKlipperSdInfo::manufacturerIdChanged ()\fC [signal]\fP"

.SS "QString QKlipperSdInfo::oemId () const"

.SS "void QKlipperSdInfo::oemIdChanged ()\fC [signal]\fP"

.SS "bool QKlipperSdInfo::operator!= (const \fBQKlipperSdInfo\fP & value)"

.SS "bool QKlipperSdInfo::operator!= (\fBQKlipperSdInfo\fP && value)"

.SS "\fBQKlipperSdInfo\fP & QKlipperSdInfo::operator= (const \fBQKlipperSdInfo\fP & value)"

.SS "\fBQKlipperSdInfo\fP & QKlipperSdInfo::operator= (\fBQKlipperSdInfo\fP && value)"

.SS "bool QKlipperSdInfo::operator== (const \fBQKlipperSdInfo\fP & value)"

.SS "bool QKlipperSdInfo::operator== (\fBQKlipperSdInfo\fP && value)"

.SS "QString QKlipperSdInfo::productName () const"

.SS "void QKlipperSdInfo::productNameChanged ()\fC [signal]\fP"

.SS "QString QKlipperSdInfo::productRevision () const"

.SS "void QKlipperSdInfo::productRevisionChanged ()\fC [signal]\fP"

.SS "QString QKlipperSdInfo::serialNumber () const"

.SS "void QKlipperSdInfo::serialNumberChanged ()\fC [signal]\fP"

.SS "void QKlipperSdInfo::setAvailableBytes (qint64 availableBytes)\fC [slot]\fP"

.SS "void QKlipperSdInfo::setCapacityString (const QString & capacityString)\fC [slot]\fP"

.SS "void QKlipperSdInfo::setManufacturer (const QString & manufacturer)\fC [slot]\fP"

.SS "void QKlipperSdInfo::setManufacturerDate (const QString & manufacturerDate)\fC [slot]\fP"

.SS "void QKlipperSdInfo::setManufacturerId (const QString & manufacturerId)\fC [slot]\fP"

.SS "void QKlipperSdInfo::setOemId (const QString & oemId)\fC [slot]\fP"

.SS "void QKlipperSdInfo::setProductName (const QString & productName)\fC [slot]\fP"

.SS "void QKlipperSdInfo::setProductRevision (const QString & productRevision)\fC [slot]\fP"

.SS "void QKlipperSdInfo::setSerialNumber (const QString & serialNumber)\fC [slot]\fP"

.SS "void QKlipperSdInfo::setTotalBytes (qint64 totalBytes)\fC [slot]\fP"

.SS "void QKlipperSdInfo::setUsedBytes (qint64 usedBytes)\fC [slot]\fP"

.SS "qint64 QKlipperSdInfo::totalBytes () const"

.SS "void QKlipperSdInfo::totalBytesChanged ()\fC [signal]\fP"

.SS "qint64 QKlipperSdInfo::usedBytes () const"

.SS "void QKlipperSdInfo::usedBytesChanged ()\fC [signal]\fP"

.SH "Property Documentation"
.PP 
.SS "qint64 QKlipperSdInfo::availableBytes\fC [read]\fP, \fC [write]\fP"

.SS "QString QKlipperSdInfo::capacityString\fC [read]\fP, \fC [write]\fP"

.SS "QString QKlipperSdInfo::manufacturer\fC [read]\fP, \fC [write]\fP"

.SS "QString QKlipperSdInfo::manufacturerDate\fC [read]\fP, \fC [write]\fP"

.SS "QString QKlipperSdInfo::manufacturerId\fC [read]\fP, \fC [write]\fP"

.SS "QString QKlipperSdInfo::oemId\fC [read]\fP, \fC [write]\fP"

.SS "QString QKlipperSdInfo::productName\fC [read]\fP, \fC [write]\fP"

.SS "QString QKlipperSdInfo::productRevision\fC [read]\fP, \fC [write]\fP"

.SS "QString QKlipperSdInfo::serialNumber\fC [read]\fP, \fC [write]\fP"

.SS "qint64 QKlipperSdInfo::totalBytes\fC [read]\fP, \fC [write]\fP"

.SS "qint64 QKlipperSdInfo::usedBytes\fC [read]\fP, \fC [write]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for QKlipper from the source code\&.
