.TH "QKlipperFile" 3 "Version 0.2" "QKlipper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QKlipperFile
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qklipperfile\&.h>\fP
.PP
Inherits QObject\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBFileType\fP { \fBGCode\fP, \fBGCodeMacro\fP, \fBConfig\fP, \fBDirectory\fP }"
.br
.in -1c
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBsetRoot\fP (const QString &\fBroot\fP)"
.br
.ti -1c
.RI "void \fBresetRoot\fP ()"
.br
.ti -1c
.RI "void \fBsetFilename\fP (const QString &\fBfilename\fP)"
.br
.ti -1c
.RI "void \fBresetFilename\fP ()"
.br
.ti -1c
.RI "void \fBsetFileType\fP (\fBFileType\fP \fBfileType\fP)"
.br
.ti -1c
.RI "void \fBresetFileType\fP ()"
.br
.ti -1c
.RI "void \fBsetMetadata\fP (const \fBQKlipperMetadata\fP &\fBmetadata\fP)"
.br
.ti -1c
.RI "void \fBresetMetadata\fP ()"
.br
.ti -1c
.RI "void \fBsetPath\fP (const QString &\fBpath\fP)"
.br
.ti -1c
.RI "void \fBresetPath\fP ()"
.br
.ti -1c
.RI "void \fBsetUuid\fP (const QString &\fBuuid\fP)"
.br
.ti -1c
.RI "void \fBsetFileSize\fP (qint64 \fBfileSize\fP)"
.br
.ti -1c
.RI "void \fBsetDateModified\fP (qreal \fBdateModified\fP)"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBrootChanged\fP ()"
.br
.ti -1c
.RI "void \fBcurrentDirectoryChanged\fP ()"
.br
.ti -1c
.RI "void \fBfilenameChanged\fP ()"
.br
.ti -1c
.RI "void \fBfileTypeChanged\fP ()"
.br
.ti -1c
.RI "void \fBmetadataChanged\fP ()"
.br
.ti -1c
.RI "void \fBpathChanged\fP ()"
.br
.ti -1c
.RI "void \fBuuidChanged\fP ()"
.br
.ti -1c
.RI "void \fBfileSizeChanged\fP ()"
.br
.ti -1c
.RI "void \fBdateModifiedChanged\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQKlipperFile\fP (QObject *parent=nullptr)"
.br
.ti -1c
.RI "QString \fBroot\fP () const"
.br
.ti -1c
.RI "QString \fBfilename\fP () const"
.br
.ti -1c
.RI "QString \fBuri\fP () const"
.br
.ti -1c
.RI "\fBFileType\fP \fBfileType\fP () const"
.br
.ti -1c
.RI "\fBQKlipperMetadata\fP \fBmetadata\fP () const"
.br
.ti -1c
.RI "QString \fBpath\fP () const"
.br
.ti -1c
.RI "QString \fBuuid\fP () const"
.br
.ti -1c
.RI "qint64 \fBfileSize\fP () const"
.br
.ti -1c
.RI "qreal \fBdateModified\fP () const"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "QString \fBroot\fP"
.br
.ti -1c
.RI "QString \fBfilename\fP"
.br
.ti -1c
.RI "\fBFileType\fP \fBfileType\fP"
.br
.ti -1c
.RI "\fBQKlipperMetadata\fP \fBmetadata\fP"
.br
.ti -1c
.RI "QString \fBuri\fP"
.br
.ti -1c
.RI "QString \fBpath\fP"
.br
.ti -1c
.RI "QString \fBuuid\fP"
.br
.ti -1c
.RI "qint64 \fBfileSize\fP"
.br
.ti -1c
.RI "qreal \fBdateModified\fP"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBQKlipperFile::FileType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIGCode \fP\fP
.TP
\fB\fIGCodeMacro \fP\fP
.TP
\fB\fIConfig \fP\fP
.TP
\fB\fIDirectory \fP\fP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QKlipperFile::QKlipperFile (QObject * parent = \fCnullptr\fP)\fC [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void QKlipperFile::currentDirectoryChanged ()\fC [signal]\fP"

.SS "qreal QKlipperFile::dateModified () const"

.SS "void QKlipperFile::dateModifiedChanged ()\fC [signal]\fP"

.SS "QString QKlipperFile::filename () const"

.SS "void QKlipperFile::filenameChanged ()\fC [signal]\fP"

.SS "qint64 QKlipperFile::fileSize () const"

.SS "void QKlipperFile::fileSizeChanged ()\fC [signal]\fP"

.SS "\fBQKlipperFile::FileType\fP QKlipperFile::fileType () const"

.SS "void QKlipperFile::fileTypeChanged ()\fC [signal]\fP"

.SS "\fBQKlipperMetadata\fP QKlipperFile::metadata () const"

.SS "void QKlipperFile::metadataChanged ()\fC [signal]\fP"

.SS "QString QKlipperFile::path () const"

.SS "void QKlipperFile::pathChanged ()\fC [signal]\fP"

.SS "void QKlipperFile::resetFilename ()\fC [slot]\fP"

.SS "void QKlipperFile::resetFileType ()\fC [slot]\fP"

.SS "void QKlipperFile::resetMetadata ()\fC [slot]\fP"

.SS "void QKlipperFile::resetPath ()\fC [slot]\fP"

.SS "void QKlipperFile::resetRoot ()\fC [slot]\fP"

.SS "QString QKlipperFile::root () const"

.SS "void QKlipperFile::rootChanged ()\fC [signal]\fP"

.SS "void QKlipperFile::setDateModified (qreal dateModified)\fC [slot]\fP"

.SS "void QKlipperFile::setFilename (const QString & filename)\fC [slot]\fP"

.SS "void QKlipperFile::setFileSize (qint64 fileSize)\fC [slot]\fP"

.SS "void QKlipperFile::setFileType (\fBFileType\fP fileType)\fC [slot]\fP"

.SS "void QKlipperFile::setMetadata (const \fBQKlipperMetadata\fP & metadata)\fC [slot]\fP"

.SS "void QKlipperFile::setPath (const QString & path)\fC [slot]\fP"

.SS "void QKlipperFile::setRoot (const QString & root)\fC [slot]\fP"

.SS "void QKlipperFile::setUuid (const QString & uuid)\fC [slot]\fP"

.SS "QString QKlipperFile::uri () const"

.SS "QString QKlipperFile::uuid () const"

.SS "void QKlipperFile::uuidChanged ()\fC [signal]\fP"

.SH "Property Documentation"
.PP 
.SS "qreal QKlipperFile::dateModified\fC [read]\fP, \fC [write]\fP"

.SS "QString QKlipperFile::filename\fC [read]\fP, \fC [write]\fP"

.SS "qint64 QKlipperFile::fileSize\fC [read]\fP, \fC [write]\fP"

.SS "\fBFileType\fP QKlipperFile::fileType\fC [read]\fP, \fC [write]\fP"

.SS "\fBQKlipperMetadata\fP QKlipperFile::metadata\fC [read]\fP, \fC [write]\fP"

.SS "QString QKlipperFile::path\fC [read]\fP, \fC [write]\fP"

.SS "QString QKlipperFile::root\fC [read]\fP, \fC [write]\fP"

.SS "QString QKlipperFile::uri\fC [read]\fP"

.SS "QString QKlipperFile::uuid\fC [read]\fP, \fC [write]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for QKlipper from the source code\&.
