.TH "QKlipperDistributionInfo" 3 "Version 0.2" "QKlipper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QKlipperDistributionInfo \- Filled by machine\&.system_info\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qklipperdistributioninfo\&.h>\fP
.PP
Inherits QObject\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBsetName\fP (const QString &\fBname\fP)"
.br
.ti -1c
.RI "void \fBsetId\fP (const QString &\fBid\fP)"
.br
.ti -1c
.RI "void \fBsetVersion\fP (const QString &\fBversion\fP)"
.br
.ti -1c
.RI "void \fBsetVersionMajor\fP (const QString &\fBversionMajor\fP)"
.br
.ti -1c
.RI "void \fBsetVersionMinor\fP (const QString &\fBversionMinor\fP)"
.br
.ti -1c
.RI "void \fBsetVersionBuildNumber\fP (const QString &\fBversionBuildNumber\fP)"
.br
.ti -1c
.RI "void \fBsetStyle\fP (const QString &\fBstyle\fP)"
.br
.ti -1c
.RI "void \fBsetCodename\fP (const QString &\fBcodename\fP)"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBnameChanged\fP ()"
.br
.ti -1c
.RI "void \fBidChanged\fP ()"
.br
.ti -1c
.RI "void \fBversionChanged\fP ()"
.br
.ti -1c
.RI "void \fBversionMajorChanged\fP ()"
.br
.ti -1c
.RI "void \fBversionMinorChanged\fP ()"
.br
.ti -1c
.RI "void \fBversionBuildNumberChanged\fP ()"
.br
.ti -1c
.RI "void \fBstyleChanged\fP ()"
.br
.ti -1c
.RI "void \fBcodenameChanged\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQKlipperDistributionInfo\fP (QObject *parent=nullptr)"
.br
.ti -1c
.RI "\fBQKlipperDistributionInfo\fP (const \fBQKlipperDistributionInfo\fP &value)"
.br
.ti -1c
.RI "\fBQKlipperDistributionInfo\fP (\fBQKlipperDistributionInfo\fP &&value)"
.br
.ti -1c
.RI "\fBQKlipperDistributionInfo\fP & \fBoperator=\fP (const \fBQKlipperDistributionInfo\fP &value)"
.br
.ti -1c
.RI "\fBQKlipperDistributionInfo\fP & \fBoperator=\fP (\fBQKlipperDistributionInfo\fP &&value)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBQKlipperDistributionInfo\fP &value)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (\fBQKlipperDistributionInfo\fP &&value)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBQKlipperDistributionInfo\fP &value)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (\fBQKlipperDistributionInfo\fP &&value)"
.br
.ti -1c
.RI "QString \fBname\fP () const"
.br
.ti -1c
.RI "QString \fBid\fP () const"
.br
.ti -1c
.RI "QString \fBversion\fP () const"
.br
.ti -1c
.RI "QString \fBversionMajor\fP () const"
.br
.ti -1c
.RI "QString \fBversionMinor\fP () const"
.br
.ti -1c
.RI "QString \fBversionBuildNumber\fP () const"
.br
.ti -1c
.RI "QString \fBstyle\fP () const"
.br
.ti -1c
.RI "QString \fBcodename\fP () const"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "QString \fBname\fP"
.br
.ti -1c
.RI "QString \fBid\fP"
.br
.ti -1c
.RI "QString \fBversion\fP"
.br
.ti -1c
.RI "QString \fBversionMajor\fP"
.br
.ti -1c
.RI "QString \fBversionMinor\fP"
.br
.ti -1c
.RI "QString \fBversionBuildNumber\fP"
.br
.ti -1c
.RI "QString \fBstyle\fP"
.br
.ti -1c
.RI "QString \fBcodename\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Filled by machine\&.system_info\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QKlipperDistributionInfo::QKlipperDistributionInfo (QObject * parent = \fCnullptr\fP)\fC [explicit]\fP"

.SS "QKlipperDistributionInfo::QKlipperDistributionInfo (const \fBQKlipperDistributionInfo\fP & value)"

.SS "QKlipperDistributionInfo::QKlipperDistributionInfo (\fBQKlipperDistributionInfo\fP && value)"

.SH "Member Function Documentation"
.PP 
.SS "QString QKlipperDistributionInfo::codename () const"

.SS "void QKlipperDistributionInfo::codenameChanged ()\fC [signal]\fP"

.SS "QString QKlipperDistributionInfo::id () const"

.SS "void QKlipperDistributionInfo::idChanged ()\fC [signal]\fP"

.SS "QString QKlipperDistributionInfo::name () const"

.SS "void QKlipperDistributionInfo::nameChanged ()\fC [signal]\fP"

.SS "bool QKlipperDistributionInfo::operator!= (const \fBQKlipperDistributionInfo\fP & value)"

.SS "bool QKlipperDistributionInfo::operator!= (\fBQKlipperDistributionInfo\fP && value)"

.SS "\fBQKlipperDistributionInfo\fP & QKlipperDistributionInfo::operator= (const \fBQKlipperDistributionInfo\fP & value)"

.SS "\fBQKlipperDistributionInfo\fP & QKlipperDistributionInfo::operator= (\fBQKlipperDistributionInfo\fP && value)"

.SS "bool QKlipperDistributionInfo::operator== (const \fBQKlipperDistributionInfo\fP & value)"

.SS "bool QKlipperDistributionInfo::operator== (\fBQKlipperDistributionInfo\fP && value)"

.SS "void QKlipperDistributionInfo::setCodename (const QString & codename)\fC [slot]\fP"

.SS "void QKlipperDistributionInfo::setId (const QString & id)\fC [slot]\fP"

.SS "void QKlipperDistributionInfo::setName (const QString & name)\fC [slot]\fP"

.SS "void QKlipperDistributionInfo::setStyle (const QString & style)\fC [slot]\fP"

.SS "void QKlipperDistributionInfo::setVersion (const QString & version)\fC [slot]\fP"

.SS "void QKlipperDistributionInfo::setVersionBuildNumber (const QString & versionBuildNumber)\fC [slot]\fP"

.SS "void QKlipperDistributionInfo::setVersionMajor (const QString & versionMajor)\fC [slot]\fP"

.SS "void QKlipperDistributionInfo::setVersionMinor (const QString & versionMinor)\fC [slot]\fP"

.SS "QString QKlipperDistributionInfo::style () const"

.SS "void QKlipperDistributionInfo::styleChanged ()\fC [signal]\fP"

.SS "QString QKlipperDistributionInfo::version () const"

.SS "QString QKlipperDistributionInfo::versionBuildNumber () const"

.SS "void QKlipperDistributionInfo::versionBuildNumberChanged ()\fC [signal]\fP"

.SS "void QKlipperDistributionInfo::versionChanged ()\fC [signal]\fP"

.SS "QString QKlipperDistributionInfo::versionMajor () const"

.SS "void QKlipperDistributionInfo::versionMajorChanged ()\fC [signal]\fP"

.SS "QString QKlipperDistributionInfo::versionMinor () const"

.SS "void QKlipperDistributionInfo::versionMinorChanged ()\fC [signal]\fP"

.SH "Property Documentation"
.PP 
.SS "QString QKlipperDistributionInfo::codename\fC [read]\fP, \fC [write]\fP"

.SS "QString QKlipperDistributionInfo::id\fC [read]\fP, \fC [write]\fP"

.SS "QString QKlipperDistributionInfo::name\fC [read]\fP, \fC [write]\fP"

.SS "QString QKlipperDistributionInfo::style\fC [read]\fP, \fC [write]\fP"

.SS "QString QKlipperDistributionInfo::version\fC [read]\fP, \fC [write]\fP"

.SS "QString QKlipperDistributionInfo::versionBuildNumber\fC [read]\fP, \fC [write]\fP"

.SS "QString QKlipperDistributionInfo::versionMajor\fC [read]\fP, \fC [write]\fP"

.SS "QString QKlipperDistributionInfo::versionMinor\fC [read]\fP, \fC [write]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for QKlipper from the source code\&.
