.TH "QKlipperSerialPeripheral" 3 "Version 0.2" "QKlipper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QKlipperSerialPeripheral \- Filled by machine\&.peripherals\&.serial\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qklipperserialperipheral\&.h>\fP
.PP
Inherits QObject\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBsetType\fP (const QString &\fBtype\fP)"
.br
.ti -1c
.RI "void \fBsetPath\fP (const QString &\fBpath\fP)"
.br
.ti -1c
.RI "void \fBsetName\fP (const QString &\fBname\fP)"
.br
.ti -1c
.RI "void \fBsetDriver\fP (const QString &\fBdriver\fP)"
.br
.ti -1c
.RI "void \fBsetHardwarePath\fP (const QString &\fBhardwarePath\fP)"
.br
.ti -1c
.RI "void \fBsetPathById\fP (const QString &\fBpathById\fP)"
.br
.ti -1c
.RI "void \fBsetUsbLocation\fP (const QString &\fBusbLocation\fP)"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBtypeChanged\fP ()"
.br
.ti -1c
.RI "void \fBpathChanged\fP ()"
.br
.ti -1c
.RI "void \fBnameChanged\fP ()"
.br
.ti -1c
.RI "void \fBdriverChanged\fP ()"
.br
.ti -1c
.RI "void \fBhardwarePathChanged\fP ()"
.br
.ti -1c
.RI "void \fBpathByIdChanged\fP ()"
.br
.ti -1c
.RI "void \fBusbLocationChanged\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQKlipperSerialPeripheral\fP (QObject *parent=nullptr)"
.br
.ti -1c
.RI "\fBQKlipperSerialPeripheral\fP (const \fBQKlipperSerialPeripheral\fP &value)"
.br
.ti -1c
.RI "\fBQKlipperSerialPeripheral\fP (\fBQKlipperSerialPeripheral\fP &&value)"
.br
.ti -1c
.RI "\fBQKlipperSerialPeripheral\fP & \fBoperator=\fP (const \fBQKlipperSerialPeripheral\fP &value)"
.br
.ti -1c
.RI "\fBQKlipperSerialPeripheral\fP & \fBoperator=\fP (\fBQKlipperSerialPeripheral\fP &&value)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBQKlipperSerialPeripheral\fP &value)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (\fBQKlipperSerialPeripheral\fP &&value)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBQKlipperSerialPeripheral\fP &value)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (\fBQKlipperSerialPeripheral\fP &&value)"
.br
.ti -1c
.RI "QString \fBtype\fP () const"
.br
.ti -1c
.RI "QString \fBpath\fP () const"
.br
.ti -1c
.RI "QString \fBname\fP () const"
.br
.ti -1c
.RI "QString \fBdriver\fP () const"
.br
.ti -1c
.RI "QString \fBhardwarePath\fP () const"
.br
.ti -1c
.RI "QString \fBpathById\fP () const"
.br
.ti -1c
.RI "QString \fBusbLocation\fP () const"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "QString \fBtype\fP"
.br
.ti -1c
.RI "QString \fBpath\fP"
.br
.ti -1c
.RI "QString \fBname\fP"
.br
.ti -1c
.RI "QString \fBdriver\fP"
.br
.ti -1c
.RI "QString \fBhardwarePath\fP"
.br
.ti -1c
.RI "QString \fBpathById\fP"
.br
.ti -1c
.RI "QString \fBusbLocation\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Filled by machine\&.peripherals\&.serial\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QKlipperSerialPeripheral::QKlipperSerialPeripheral (QObject * parent = \fCnullptr\fP)\fC [explicit]\fP"

.SS "QKlipperSerialPeripheral::QKlipperSerialPeripheral (const \fBQKlipperSerialPeripheral\fP & value)"

.SS "QKlipperSerialPeripheral::QKlipperSerialPeripheral (\fBQKlipperSerialPeripheral\fP && value)"

.SH "Member Function Documentation"
.PP 
.SS "QString QKlipperSerialPeripheral::driver () const"

.SS "void QKlipperSerialPeripheral::driverChanged ()\fC [signal]\fP"

.SS "QString QKlipperSerialPeripheral::hardwarePath () const"

.SS "void QKlipperSerialPeripheral::hardwarePathChanged ()\fC [signal]\fP"

.SS "QString QKlipperSerialPeripheral::name () const"

.SS "void QKlipperSerialPeripheral::nameChanged ()\fC [signal]\fP"

.SS "bool QKlipperSerialPeripheral::operator!= (const \fBQKlipperSerialPeripheral\fP & value)"

.SS "bool QKlipperSerialPeripheral::operator!= (\fBQKlipperSerialPeripheral\fP && value)"

.SS "\fBQKlipperSerialPeripheral\fP & QKlipperSerialPeripheral::operator= (const \fBQKlipperSerialPeripheral\fP & value)"

.SS "\fBQKlipperSerialPeripheral\fP & QKlipperSerialPeripheral::operator= (\fBQKlipperSerialPeripheral\fP && value)"

.SS "bool QKlipperSerialPeripheral::operator== (const \fBQKlipperSerialPeripheral\fP & value)"

.SS "bool QKlipperSerialPeripheral::operator== (\fBQKlipperSerialPeripheral\fP && value)"

.SS "QString QKlipperSerialPeripheral::path () const"

.SS "QString QKlipperSerialPeripheral::pathById () const"

.SS "void QKlipperSerialPeripheral::pathByIdChanged ()\fC [signal]\fP"

.SS "void QKlipperSerialPeripheral::pathChanged ()\fC [signal]\fP"

.SS "void QKlipperSerialPeripheral::setDriver (const QString & driver)\fC [slot]\fP"

.SS "void QKlipperSerialPeripheral::setHardwarePath (const QString & hardwarePath)\fC [slot]\fP"

.SS "void QKlipperSerialPeripheral::setName (const QString & name)\fC [slot]\fP"

.SS "void QKlipperSerialPeripheral::setPath (const QString & path)\fC [slot]\fP"

.SS "void QKlipperSerialPeripheral::setPathById (const QString & pathById)\fC [slot]\fP"

.SS "void QKlipperSerialPeripheral::setType (const QString & type)\fC [slot]\fP"

.SS "void QKlipperSerialPeripheral::setUsbLocation (const QString & usbLocation)\fC [slot]\fP"

.SS "QString QKlipperSerialPeripheral::type () const"

.SS "void QKlipperSerialPeripheral::typeChanged ()\fC [signal]\fP"

.SS "QString QKlipperSerialPeripheral::usbLocation () const"

.SS "void QKlipperSerialPeripheral::usbLocationChanged ()\fC [signal]\fP"

.SH "Property Documentation"
.PP 
.SS "QString QKlipperSerialPeripheral::driver\fC [read]\fP, \fC [write]\fP"

.SS "QString QKlipperSerialPeripheral::hardwarePath\fC [read]\fP, \fC [write]\fP"

.SS "QString QKlipperSerialPeripheral::name\fC [read]\fP, \fC [write]\fP"

.SS "QString QKlipperSerialPeripheral::path\fC [read]\fP, \fC [write]\fP"

.SS "QString QKlipperSerialPeripheral::pathById\fC [read]\fP, \fC [write]\fP"

.SS "QString QKlipperSerialPeripheral::type\fC [read]\fP, \fC [write]\fP"

.SS "QString QKlipperSerialPeripheral::usbLocation\fC [read]\fP, \fC [write]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for QKlipper from the source code\&.
