.TH "QKlipperLibcameraDevice" 3 "Version 0.2" "QKlipper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QKlipperLibcameraDevice \- Filled by machine\&.peripherals\&.serial\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qklipperlibcameradevice\&.h>\fP
.PP
Inherits QObject\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBsetId\fP (const QString &\fBid\fP)"
.br
.ti -1c
.RI "void \fBsetModel\fP (const QString &\fBmodel\fP)"
.br
.ti -1c
.RI "void \fBsetModes\fP (const QList< \fBQKlipperLibCameraMode\fP > &\fBmodes\fP)"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBidChanged\fP ()"
.br
.ti -1c
.RI "void \fBmodelChanged\fP ()"
.br
.ti -1c
.RI "void \fBmodesChanged\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQKlipperLibcameraDevice\fP (QObject *parent=nullptr)"
.br
.ti -1c
.RI "\fBQKlipperLibcameraDevice\fP (const \fBQKlipperLibcameraDevice\fP &value)"
.br
.ti -1c
.RI "\fBQKlipperLibcameraDevice\fP (\fBQKlipperLibcameraDevice\fP &&value)"
.br
.ti -1c
.RI "\fBQKlipperLibcameraDevice\fP & \fBoperator=\fP (const \fBQKlipperLibcameraDevice\fP &value)"
.br
.ti -1c
.RI "\fBQKlipperLibcameraDevice\fP & \fBoperator=\fP (\fBQKlipperLibcameraDevice\fP &&value)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBQKlipperLibcameraDevice\fP &value) const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (\fBQKlipperLibcameraDevice\fP &&value)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBQKlipperLibcameraDevice\fP &value)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (\fBQKlipperLibcameraDevice\fP &&value)"
.br
.ti -1c
.RI "QString \fBid\fP () const"
.br
.ti -1c
.RI "QString \fBmodel\fP () const"
.br
.ti -1c
.RI "QList< \fBQKlipperLibCameraMode\fP > \fBmodes\fP () const"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "QString \fBid\fP"
.br
.ti -1c
.RI "QString \fBmodel\fP"
.br
.ti -1c
.RI "QList< \fBQKlipperLibCameraMode\fP > \fBmodes\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Filled by machine\&.peripherals\&.serial\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QKlipperLibcameraDevice::QKlipperLibcameraDevice (QObject * parent = \fCnullptr\fP)\fC [explicit]\fP"

.SS "QKlipperLibcameraDevice::QKlipperLibcameraDevice (const \fBQKlipperLibcameraDevice\fP & value)"

.SS "QKlipperLibcameraDevice::QKlipperLibcameraDevice (\fBQKlipperLibcameraDevice\fP && value)"

.SH "Member Function Documentation"
.PP 
.SS "QString QKlipperLibcameraDevice::id () const"

.SS "void QKlipperLibcameraDevice::idChanged ()\fC [signal]\fP"

.SS "QString QKlipperLibcameraDevice::model () const"

.SS "void QKlipperLibcameraDevice::modelChanged ()\fC [signal]\fP"

.SS "QList< \fBQKlipperLibCameraMode\fP > QKlipperLibcameraDevice::modes () const"

.SS "void QKlipperLibcameraDevice::modesChanged ()\fC [signal]\fP"

.SS "bool QKlipperLibcameraDevice::operator!= (const \fBQKlipperLibcameraDevice\fP & value)"

.SS "bool QKlipperLibcameraDevice::operator!= (\fBQKlipperLibcameraDevice\fP && value)"

.SS "\fBQKlipperLibcameraDevice\fP & QKlipperLibcameraDevice::operator= (const \fBQKlipperLibcameraDevice\fP & value)"

.SS "\fBQKlipperLibcameraDevice\fP & QKlipperLibcameraDevice::operator= (\fBQKlipperLibcameraDevice\fP && value)"

.SS "bool QKlipperLibcameraDevice::operator== (const \fBQKlipperLibcameraDevice\fP & value) const"

.SS "bool QKlipperLibcameraDevice::operator== (\fBQKlipperLibcameraDevice\fP && value)"

.SS "void QKlipperLibcameraDevice::setId (const QString & id)\fC [slot]\fP"

.SS "void QKlipperLibcameraDevice::setModel (const QString & model)\fC [slot]\fP"

.SS "void QKlipperLibcameraDevice::setModes (const QList< \fBQKlipperLibCameraMode\fP > & modes)\fC [slot]\fP"

.SH "Property Documentation"
.PP 
.SS "QString QKlipperLibcameraDevice::id\fC [read]\fP, \fC [write]\fP"

.SS "QString QKlipperLibcameraDevice::model\fC [read]\fP, \fC [write]\fP"

.SS "QList<\fBQKlipperLibCameraMode\fP> QKlipperLibcameraDevice::modes\fC [read]\fP, \fC [write]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for QKlipper from the source code\&.
