.TH "QKlipperChamber" 3 "Version 0.2" "QKlipper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QKlipperChamber
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qklipperchamber\&.h>\fP
.PP
Inherits QObject\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQKlipperChamber\fP (QObject *parent=nullptr)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QKlipperChamber::QKlipperChamber (QObject * parent = \fCnullptr\fP)\fC [explicit]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for QKlipper from the source code\&.
