.TH "QKlipperLibCameraMode" 3 "Version 0.2" "QKlipper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QKlipperLibCameraMode
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qklipperlibcameramode\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBQKlipperLibCameraMode\fP &mode) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QString \fBformat\fP"
.br
.ti -1c
.RI "QStringList \fBresolutions\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bool QKlipperLibCameraMode::operator== (const \fBQKlipperLibCameraMode\fP & mode) const\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "QString QKlipperLibCameraMode::format"

.SS "QStringList QKlipperLibCameraMode::resolutions"


.SH "Author"
.PP 
Generated automatically by Doxygen for QKlipper from the source code\&.
