.TH "/home/parametheus/repo/QKlipper/QKlipperServer/qklipperprintjob.h" 3 "Version 0.2" "QKlipper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/parametheus/repo/QKlipper/QKlipperServer/qklipperprintjob.h
.SH SYNOPSIS
.br
.PP
\fC#include <QObject>\fP
.br
\fC#include <QVariant>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBQKlipperPrintJob\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QKlipper from the source code\&.
