.TH "QKlipperGCodeStore" 3 "Version 0.2" "QKlipper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QKlipperGCodeStore
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qklippergcodestore\&.h>\fP
.PP
Inherits QObject\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBsetValues\fP (const QList< \fBQKlipperGCodeStoreValue\fP > &\fBvalues\fP)"
.br
.ti -1c
.RI "void \fBsetValue\fP (const \fBQKlipperGCodeStoreValue\fP &\fBvalue\fP)"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBvaluesChanged\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQKlipperGCodeStore\fP (QObject *parent=nullptr)"
.br
.ti -1c
.RI "QList< \fBQKlipperGCodeStoreValue\fP > \fBvalues\fP () const"
.br
.ti -1c
.RI "\fBQKlipperGCodeStoreValue\fP \fBvalue\fP (qint32 index) const"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "QList< \fBQKlipperGCodeStoreValue\fP > \fBvalues\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QKlipperGCodeStore::QKlipperGCodeStore (QObject * parent = \fCnullptr\fP)\fC [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void QKlipperGCodeStore::setValue (const \fBQKlipperGCodeStoreValue\fP & value)\fC [slot]\fP"

.SS "void QKlipperGCodeStore::setValues (const QList< \fBQKlipperGCodeStoreValue\fP > & values)\fC [slot]\fP"

.SS "\fBQKlipperGCodeStoreValue\fP QKlipperGCodeStore::value (qint32 index) const"

.SS "QList< \fBQKlipperGCodeStoreValue\fP > QKlipperGCodeStore::values () const"

.SS "void QKlipperGCodeStore::valuesChanged ()\fC [signal]\fP"

.SH "Property Documentation"
.PP 
.SS "QList<\fBQKlipperGCodeStoreValue\fP> QKlipperGCodeStore::values\fC [read]\fP, \fC [write]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for QKlipper from the source code\&.
