.TH "QKlipperServiceState" 3 "Version 0.2" "QKlipper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QKlipperServiceState
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qklipperservicestate\&.h>\fP
.PP
Inherits QObject\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBsetActiveState\fP (const QString &\fBactiveState\fP)"
.br
.ti -1c
.RI "void \fBsetSubState\fP (const QString &\fBsubState\fP)"
.br
.ti -1c
.RI "void \fBsetName\fP (const QString &\fBname\fP)"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBactiveStateChanged\fP ()"
.br
.ti -1c
.RI "void \fBsubStateChanged\fP ()"
.br
.ti -1c
.RI "void \fBnameChanged\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQKlipperServiceState\fP (QObject *parent=nullptr)"
.br
.ti -1c
.RI "\fB~QKlipperServiceState\fP ()"
.br
.ti -1c
.RI "\fBQKlipperServiceState\fP (const \fBQKlipperServiceState\fP &value)"
.br
.ti -1c
.RI "\fBQKlipperServiceState\fP (\fBQKlipperServiceState\fP &&value)"
.br
.ti -1c
.RI "\fBQKlipperServiceState\fP & \fBoperator=\fP (const \fBQKlipperServiceState\fP &value)"
.br
.ti -1c
.RI "\fBQKlipperServiceState\fP & \fBoperator=\fP (\fBQKlipperServiceState\fP &&value)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBQKlipperServiceState\fP &value)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (\fBQKlipperServiceState\fP &&value)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBQKlipperServiceState\fP &value)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (\fBQKlipperServiceState\fP &&value)"
.br
.ti -1c
.RI "QString \fBactiveState\fP () const"
.br
.ti -1c
.RI "QString \fBsubState\fP () const"
.br
.ti -1c
.RI "QString \fBname\fP () const"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "QString \fBactiveState\fP"
.br
.ti -1c
.RI "QString \fBsubState\fP"
.br
.ti -1c
.RI "QString \fBname\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QKlipperServiceState::QKlipperServiceState (QObject * parent = \fCnullptr\fP)\fC [explicit]\fP"

.SS "QKlipperServiceState::~QKlipperServiceState ()"

.SS "QKlipperServiceState::QKlipperServiceState (const \fBQKlipperServiceState\fP & value)"

.SS "QKlipperServiceState::QKlipperServiceState (\fBQKlipperServiceState\fP && value)"

.SH "Member Function Documentation"
.PP 
.SS "QString QKlipperServiceState::activeState () const"

.SS "void QKlipperServiceState::activeStateChanged ()\fC [signal]\fP"

.SS "QString QKlipperServiceState::name () const"

.SS "void QKlipperServiceState::nameChanged ()\fC [signal]\fP"

.SS "bool QKlipperServiceState::operator!= (const \fBQKlipperServiceState\fP & value)"

.SS "bool QKlipperServiceState::operator!= (\fBQKlipperServiceState\fP && value)"

.SS "\fBQKlipperServiceState\fP & QKlipperServiceState::operator= (const \fBQKlipperServiceState\fP & value)"

.SS "\fBQKlipperServiceState\fP & QKlipperServiceState::operator= (\fBQKlipperServiceState\fP && value)"

.SS "bool QKlipperServiceState::operator== (const \fBQKlipperServiceState\fP & value)"

.SS "bool QKlipperServiceState::operator== (\fBQKlipperServiceState\fP && value)"

.SS "void QKlipperServiceState::setActiveState (const QString & activeState)\fC [slot]\fP"

.SS "void QKlipperServiceState::setName (const QString & name)\fC [slot]\fP"

.SS "void QKlipperServiceState::setSubState (const QString & subState)\fC [slot]\fP"

.SS "QString QKlipperServiceState::subState () const"

.SS "void QKlipperServiceState::subStateChanged ()\fC [signal]\fP"

.SH "Property Documentation"
.PP 
.SS "QString QKlipperServiceState::activeState\fC [read]\fP, \fC [write]\fP"

.SS "QString QKlipperServiceState::name\fC [read]\fP, \fC [write]\fP"

.SS "QString QKlipperServiceState::subState\fC [read]\fP, \fC [write]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for QKlipper from the source code\&.
