.TH "QKlipperPrintBedMesh::Limit" 3 "Version 0.2" "QKlipper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QKlipperPrintBedMesh::Limit \- \fBLimit\fP struct\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qklipperprintbedmesh\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "qreal \fBx\fP"
.br
.ti -1c
.RI "qreal \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBLimit\fP struct\&. 

This struct provides an x/y coordinate pair 
.SH "Member Data Documentation"
.PP 
.SS "qreal QKlipperPrintBedMesh::Limit::x"

.SS "qreal QKlipperPrintBedMesh::Limit::y"


.SH "Author"
.PP 
Generated automatically by Doxygen for QKlipper from the source code\&.
