.TH "/home/parametheus/repo/QKlipper/QKlipperSystem/qklipperupdatepackage.h" 3 "Version 0.2" "QKlipper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/parametheus/repo/QKlipper/QKlipperSystem/qklipperupdatepackage.h
.SH SYNOPSIS
.br
.PP
\fC#include <QObject>\fP
.br
\fC#include 'qklipperupdatecommit\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBQKlipperUpdatePackage\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QKlipper from the source code\&.
