.TH "/home/parametheus/repo/QKlipper/QKlipperSystem/qklipperserialperipheral.h" 3 "Version 0.2" "QKlipper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/parametheus/repo/QKlipper/QKlipperSystem/qklipperserialperipheral.h
.SH SYNOPSIS
.br
.PP
\fC#include <QObject>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBQKlipperSerialPeripheral\fP"
.br
.RI "Filled by machine\&.peripherals\&.serial\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QKlipper from the source code\&.
