.TH "/home/parametheus/repo/QKlipper/QKlipperServer/qklipperserver.h" 3 "Version 0.2" "QKlipper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/parametheus/repo/QKlipper/QKlipperServer/qklipperserver.h
.SH SYNOPSIS
.br
.PP
\fC#include <QObject>\fP
.br
\fC#include 'QKlipperFile/qklipperfile\&.h'\fP
.br
\fC#include 'qklipperclientidentifier\&.h'\fP
.br
\fC#include 'qklippergcodestore\&.h'\fP
.br
\fC#include 'qklipperaccessdetails\&.h'\fP
.br
\fC#include 'qklipperannouncement\&.h'\fP
.br
\fC#include 'qklipperjobqueue\&.h'\fP
.br
\fC#include 'qklipperuser\&.h'\fP
.br
\fC#include 'qklippergcodemacro\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBQKlipperServer\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QKlipper from the source code\&.
