.TH "QKlipperCanBusInterface" 3 "Version 0.2" "QKlipper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QKlipperCanBusInterface
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qklippercanbusinterface\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBQKlipperCanBusInterface\fP &interface)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QString \fBuuid\fP"
.br
.ti -1c
.RI "QString \fBapplication\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bool QKlipperCanBusInterface::operator== (const \fBQKlipperCanBusInterface\fP & interface)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "QString QKlipperCanBusInterface::application"

.SS "QString QKlipperCanBusInterface::uuid"


.SH "Author"
.PP 
Generated automatically by Doxygen for QKlipper from the source code\&.
