.TH "QKlipperNetworkAddress" 3 "Version 0.2" "QKlipper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QKlipperNetworkAddress
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qklippernetworkaddress\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBQKlipperNetworkAddress\fP &\fBaddress\fP) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QString \fBfamily\fP"
.br
.ti -1c
.RI "QString \fBaddress\fP"
.br
.ti -1c
.RI "bool \fBisLinkLocal\fP = false"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bool QKlipperNetworkAddress::operator== (const \fBQKlipperNetworkAddress\fP & address) const\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "QString QKlipperNetworkAddress::address"

.SS "QString QKlipperNetworkAddress::family"

.SS "bool QKlipperNetworkAddress::isLinkLocal = false"


.SH "Author"
.PP 
Generated automatically by Doxygen for QKlipper from the source code\&.
