.TH "/home/parametheus/repo/QKlipper/QKlipperPrinter/qklipperposition.h" 3 "Version 0.2" "QKlipper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/parametheus/repo/QKlipper/QKlipperPrinter/qklipperposition.h
.SH SYNOPSIS
.br
.PP
\fC#include <QObject>\fP
.br
\fC#include <QMap>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBQKlipperPosition\fP"
.br
.RI "\fBQKlipperPosition\fP class\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QKlipper from the source code\&.
