.TH "QKlipperThumbnail" 3 "Version 0.2" "QKlipper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QKlipperThumbnail
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qklipperthumbnail\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBQKlipperThumbnail\fP &value)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "qint32 \fBwidth\fP = 0"
.br
.ti -1c
.RI "qint32 \fBheight\fP = 0"
.br
.ti -1c
.RI "qint64 \fBsize\fP = 0"
.br
.ti -1c
.RI "QString \fBrelativePath\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bool QKlipperThumbnail::operator== (const \fBQKlipperThumbnail\fP & value)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "qint32 QKlipperThumbnail::height = 0"

.SS "QString QKlipperThumbnail::relativePath"

.SS "qint64 QKlipperThumbnail::size = 0"

.SS "qint32 QKlipperThumbnail::width = 0"


.SH "Author"
.PP 
Generated automatically by Doxygen for QKlipper from the source code\&.
