.TH "QKlipperTemperatureStoreValue" 3 "Version 0.2" "QKlipper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QKlipperTemperatureStoreValue
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qklippertemperaturestore\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBQKlipperTemperatureStoreValue\fP &value)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBQKlipperTemperatureStoreValue\fP &value)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "qreal \fBtemperature\fP = 0"
.br
.ti -1c
.RI "qreal \fBpower\fP = 0"
.br
.ti -1c
.RI "qreal \fBtarget\fP = 0"
.br
.ti -1c
.RI "qreal \fBspeed\fP = 0"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bool QKlipperTemperatureStoreValue::operator!= (const \fBQKlipperTemperatureStoreValue\fP & value)\fC [inline]\fP"

.SS "bool QKlipperTemperatureStoreValue::operator== (const \fBQKlipperTemperatureStoreValue\fP & value)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "qreal QKlipperTemperatureStoreValue::power = 0"

.SS "qreal QKlipperTemperatureStoreValue::speed = 0"

.SS "qreal QKlipperTemperatureStoreValue::target = 0"

.SS "qreal QKlipperTemperatureStoreValue::temperature = 0"


.SH "Author"
.PP 
Generated automatically by Doxygen for QKlipper from the source code\&.
