.TH "QKlipperClientIdentifier" 3 "Version 0.2" "QKlipper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QKlipperClientIdentifier
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qklipperclientidentifier\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBQKlipperClientIdentifier\fP &value)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (\fBQKlipperClientIdentifier\fP &&value)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBQKlipperClientIdentifier\fP &value)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (\fBQKlipperClientIdentifier\fP &&value)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QString \fBname\fP"
.br
.ti -1c
.RI "QString \fBversion\fP"
.br
.ti -1c
.RI "QString \fBtype\fP"
.br
.ti -1c
.RI "QString \fBurl\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bool QKlipperClientIdentifier::operator!= (const \fBQKlipperClientIdentifier\fP & value)\fC [inline]\fP"

.SS "bool QKlipperClientIdentifier::operator!= (\fBQKlipperClientIdentifier\fP && value)\fC [inline]\fP"

.SS "bool QKlipperClientIdentifier::operator== (const \fBQKlipperClientIdentifier\fP & value)\fC [inline]\fP"

.SS "bool QKlipperClientIdentifier::operator== (\fBQKlipperClientIdentifier\fP && value)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "QString QKlipperClientIdentifier::name"

.SS "QString QKlipperClientIdentifier::type"

.SS "QString QKlipperClientIdentifier::url"

.SS "QString QKlipperClientIdentifier::version"


.SH "Author"
.PP 
Generated automatically by Doxygen for QKlipper from the source code\&.
