.TH "QKlipperVirtualSDCard" 3 "Version 0.2" "QKlipper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QKlipperVirtualSDCard
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qklippervirtualsdcard\&.h>\fP
.PP
Inherits QObject\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBfilePathChanged\fP ()"
.br
.ti -1c
.RI "void \fBfileSizeChanged\fP ()"
.br
.ti -1c
.RI "void \fBfilePositionChanged\fP ()"
.br
.ti -1c
.RI "void \fBisActiveChanged\fP ()"
.br
.ti -1c
.RI "void \fBprogressChanged\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQKlipperVirtualSDCard\fP (QObject *parent=nullptr)"
.br
.ti -1c
.RI "QString \fBfilePath\fP () const"
.br
.ti -1c
.RI "qint64 \fBfileSize\fP () const"
.br
.ti -1c
.RI "qint64 \fBfilePosition\fP () const"
.br
.ti -1c
.RI "bool \fBisActive\fP () const"
.br
.ti -1c
.RI "qreal \fBprogress\fP () const"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "QString \fBfilePath\fP"
.br
.ti -1c
.RI "qint64 \fBfileSize\fP"
.br
.ti -1c
.RI "qint64 \fBfilePosition\fP"
.br
.ti -1c
.RI "bool \fBisActive\fP"
.br
.ti -1c
.RI "qreal \fBprogress\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QKlipperVirtualSDCard::QKlipperVirtualSDCard (QObject * parent = \fCnullptr\fP)\fC [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "QString QKlipperVirtualSDCard::filePath () const"

.SS "void QKlipperVirtualSDCard::filePathChanged ()\fC [signal]\fP"

.SS "qint64 QKlipperVirtualSDCard::filePosition () const"

.SS "void QKlipperVirtualSDCard::filePositionChanged ()\fC [signal]\fP"

.SS "qint64 QKlipperVirtualSDCard::fileSize () const"

.SS "void QKlipperVirtualSDCard::fileSizeChanged ()\fC [signal]\fP"

.SS "bool QKlipperVirtualSDCard::isActive () const"

.SS "void QKlipperVirtualSDCard::isActiveChanged ()\fC [signal]\fP"

.SS "qreal QKlipperVirtualSDCard::progress () const"

.SS "void QKlipperVirtualSDCard::progressChanged ()\fC [signal]\fP"

.SH "Property Documentation"
.PP 
.SS "QString QKlipperVirtualSDCard::filePath\fC [read]\fP, \fC [write]\fP"

.SS "qint64 QKlipperVirtualSDCard::filePosition\fC [read]\fP, \fC [write]\fP"

.SS "qint64 QKlipperVirtualSDCard::fileSize\fC [read]\fP, \fC [write]\fP"

.SS "bool QKlipperVirtualSDCard::isActive\fC [read]\fP, \fC [write]\fP"

.SS "qreal QKlipperVirtualSDCard::progress\fC [read]\fP, \fC [write]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for QKlipper from the source code\&.
