.TH "QKlipperVirtualizationState" 3 "Version 0.2" "QKlipper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QKlipperVirtualizationState \- Filled by machine\&.system_info\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qklippervirtualizationstate\&.h>\fP
.PP
Inherits QObject\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBsetType\fP (const QString &\fBtype\fP)"
.br
.ti -1c
.RI "void \fBsetIdentifier\fP (const QString &\fBidentifier\fP)"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBtypeChanged\fP ()"
.br
.ti -1c
.RI "void \fBidentifierChanged\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQKlipperVirtualizationState\fP (QObject *parent=nullptr)"
.br
.ti -1c
.RI "QString \fBtype\fP () const"
.br
.ti -1c
.RI "QString \fBidentifier\fP () const"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "QString \fBtype\fP"
.br
.ti -1c
.RI "QString \fBidentifier\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Filled by machine\&.system_info\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QKlipperVirtualizationState::QKlipperVirtualizationState (QObject * parent = \fCnullptr\fP)\fC [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "QString QKlipperVirtualizationState::identifier () const"

.SS "void QKlipperVirtualizationState::identifierChanged ()\fC [signal]\fP"

.SS "void QKlipperVirtualizationState::setIdentifier (const QString & identifier)\fC [slot]\fP"

.SS "void QKlipperVirtualizationState::setType (const QString & type)\fC [slot]\fP"

.SS "QString QKlipperVirtualizationState::type () const"

.SS "void QKlipperVirtualizationState::typeChanged ()\fC [signal]\fP"

.SH "Property Documentation"
.PP 
.SS "QString QKlipperVirtualizationState::identifier\fC [read]\fP, \fC [write]\fP"

.SS "QString QKlipperVirtualizationState::type\fC [read]\fP, \fC [write]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for QKlipper from the source code\&.
