.TH "/home/parametheus/repo/QKlipper/QKlipperInstance/qklipperinstance.h" 3 "Version 0.2" "QKlipper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/parametheus/repo/QKlipper/QKlipperInstance/qklipperinstance.h
.SH SYNOPSIS
.br
.PP
\fC#include <QObject>\fP
.br
\fC#include <QQueue>\fP
.br
\fC#include <QByteArray>\fP
.br
\fC#include <QFunctionPointer>\fP
.br
\fC#include <QAbstractSocket>\fP
.br
\fC#include <QLocalSocket>\fP
.br
\fC#include <QTcpSocket>\fP
.br
\fC#include <QSslSocket>\fP
.br
\fC#include <QJsonArray>\fP
.br
\fC#include <QJsonDocument>\fP
.br
\fC#include <QJsonObject>\fP
.br
\fC#include <QJsonParseError>\fP
.br
\fC#include <QNetworkAccessManager>\fP
.br
\fC#include <QNetworkReply>\fP
.br
\fC#include <QNetworkRequest>\fP
.br
\fC#include 'QKlipperConsole/qklipperconsole\&.h'\fP
.br
\fC#include 'QKlipperPrinter/qklipperprinter\&.h'\fP
.br
\fC#include 'QKlipperServer/qklipperserver\&.h'\fP
.br
\fC#include 'QKlipperSystem/qklippersystem\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBQKlipperInstance\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for QKlipper from the source code\&.
