.TH "QKlipperV412Mode" 3 "Version 0.2" "QKlipper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QKlipperV412Mode
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qklipperv412mode\&.h>\fP
.PP
Inherits QObject\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBsetDescription\fP (const QString &\fBdescription\fP)"
.br
.ti -1c
.RI "void \fBsetFormat\fP (const QString &\fBformat\fP)"
.br
.ti -1c
.RI "void \fBsetFlags\fP (const QStringList &\fBflags\fP)"
.br
.ti -1c
.RI "void \fBsetResolutions\fP (const QStringList &\fBresolutions\fP)"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBdescriptionChanged\fP ()"
.br
.ti -1c
.RI "void \fBformatChanged\fP ()"
.br
.ti -1c
.RI "void \fBflagsChanged\fP ()"
.br
.ti -1c
.RI "void \fBresolutionsChanged\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQKlipperV412Mode\fP (QObject *parent=nullptr)"
.br
.ti -1c
.RI "\fBQKlipperV412Mode\fP (const \fBQKlipperV412Mode\fP &value)"
.br
.ti -1c
.RI "\fBQKlipperV412Mode\fP (\fBQKlipperV412Mode\fP &&value)"
.br
.ti -1c
.RI "\fBQKlipperV412Mode\fP & \fBoperator=\fP (const \fBQKlipperV412Mode\fP &value)"
.br
.ti -1c
.RI "\fBQKlipperV412Mode\fP & \fBoperator=\fP (\fBQKlipperV412Mode\fP &&value)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBQKlipperV412Mode\fP &value)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (\fBQKlipperV412Mode\fP &&value)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBQKlipperV412Mode\fP &value)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (\fBQKlipperV412Mode\fP &&value)"
.br
.ti -1c
.RI "QString \fBdescription\fP () const"
.br
.ti -1c
.RI "QString \fBformat\fP () const"
.br
.ti -1c
.RI "QStringList \fBflags\fP () const"
.br
.ti -1c
.RI "QStringList \fBresolutions\fP () const"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "QString \fBdescription\fP"
.br
.ti -1c
.RI "QString \fBformat\fP"
.br
.ti -1c
.RI "QStringList \fBflags\fP"
.br
.ti -1c
.RI "QStringList \fBresolutions\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QKlipperV412Mode::QKlipperV412Mode (QObject * parent = \fCnullptr\fP)\fC [explicit]\fP"

.SS "QKlipperV412Mode::QKlipperV412Mode (const \fBQKlipperV412Mode\fP & value)"

.SS "QKlipperV412Mode::QKlipperV412Mode (\fBQKlipperV412Mode\fP && value)"

.SH "Member Function Documentation"
.PP 
.SS "QString QKlipperV412Mode::description () const"

.SS "void QKlipperV412Mode::descriptionChanged ()\fC [signal]\fP"

.SS "QStringList QKlipperV412Mode::flags () const"

.SS "void QKlipperV412Mode::flagsChanged ()\fC [signal]\fP"

.SS "QString QKlipperV412Mode::format () const"

.SS "void QKlipperV412Mode::formatChanged ()\fC [signal]\fP"

.SS "bool QKlipperV412Mode::operator!= (const \fBQKlipperV412Mode\fP & value)"

.SS "bool QKlipperV412Mode::operator!= (\fBQKlipperV412Mode\fP && value)"

.SS "\fBQKlipperV412Mode\fP & QKlipperV412Mode::operator= (const \fBQKlipperV412Mode\fP & value)"

.SS "\fBQKlipperV412Mode\fP & QKlipperV412Mode::operator= (\fBQKlipperV412Mode\fP && value)"

.SS "bool QKlipperV412Mode::operator== (const \fBQKlipperV412Mode\fP & value)"

.SS "bool QKlipperV412Mode::operator== (\fBQKlipperV412Mode\fP && value)"

.SS "QStringList QKlipperV412Mode::resolutions () const"

.SS "void QKlipperV412Mode::resolutionsChanged ()\fC [signal]\fP"

.SS "void QKlipperV412Mode::setDescription (const QString & description)\fC [slot]\fP"

.SS "void QKlipperV412Mode::setFlags (const QStringList & flags)\fC [slot]\fP"

.SS "void QKlipperV412Mode::setFormat (const QString & format)\fC [slot]\fP"

.SS "void QKlipperV412Mode::setResolutions (const QStringList & resolutions)\fC [slot]\fP"

.SH "Property Documentation"
.PP 
.SS "QString QKlipperV412Mode::description\fC [read]\fP, \fC [write]\fP"

.SS "QStringList QKlipperV412Mode::flags\fC [read]\fP, \fC [write]\fP"

.SS "QString QKlipperV412Mode::format\fC [read]\fP, \fC [write]\fP"

.SS "QStringList QKlipperV412Mode::resolutions\fC [read]\fP, \fC [write]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for QKlipper from the source code\&.
