.TH "/home/parametheus/repo/QKlipper/QKlipperFile/qklipperfile.h" 3 "Version 0.2" "QKlipper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/parametheus/repo/QKlipper/QKlipperFile/qklipperfile.h
.SH SYNOPSIS
.br
.PP
\fC#include <QObject>\fP
.br
\fC#include <QString>\fP
.br
\fC#include <QDir>\fP
.br
\fC#include 'qklippermetadata\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBQKlipperFile\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef QList< \fBQKlipperFile\fP * > \fBQKlipperFileList\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef QList<\fBQKlipperFile\fP*> \fBQKlipperFileList\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for QKlipper from the source code\&.
