.TH "QKlipperNetworkStatsEntry" 3 "Version 0.2" "QKlipper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QKlipperNetworkStatsEntry \- Filled by machine\&.proc_stats\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qklippernetworkstatsentry\&.h>\fP
.PP
Inherits QObject\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBsetRxBytes\fP (qreal \fBrxBytes\fP)"
.br
.ti -1c
.RI "void \fBsetTxBytes\fP (qreal \fBtxBytes\fP)"
.br
.ti -1c
.RI "void \fBsetBandwidth\fP (qreal \fBbandwidth\fP)"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBrxBytesChanged\fP ()"
.br
.ti -1c
.RI "void \fBtxBytesChanged\fP ()"
.br
.ti -1c
.RI "void \fBbandwidthChanged\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQKlipperNetworkStatsEntry\fP (QObject *parent=nullptr)"
.br
.ti -1c
.RI "\fBQKlipperNetworkStatsEntry\fP (const \fBQKlipperNetworkStatsEntry\fP &value)"
.br
.ti -1c
.RI "\fBQKlipperNetworkStatsEntry\fP (\fBQKlipperNetworkStatsEntry\fP &&value)"
.br
.ti -1c
.RI "\fBQKlipperNetworkStatsEntry\fP & \fBoperator=\fP (const \fBQKlipperNetworkStatsEntry\fP &value)"
.br
.ti -1c
.RI "\fBQKlipperNetworkStatsEntry\fP & \fBoperator=\fP (\fBQKlipperNetworkStatsEntry\fP &&value)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBQKlipperNetworkStatsEntry\fP &value)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (\fBQKlipperNetworkStatsEntry\fP &&value)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBQKlipperNetworkStatsEntry\fP &value)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (\fBQKlipperNetworkStatsEntry\fP &&value)"
.br
.ti -1c
.RI "qreal \fBrxBytes\fP () const"
.br
.ti -1c
.RI "qreal \fBtxBytes\fP () const"
.br
.ti -1c
.RI "qreal \fBbandwidth\fP () const"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "qreal \fBrxBytes\fP"
.br
.ti -1c
.RI "qreal \fBtxBytes\fP"
.br
.ti -1c
.RI "qreal \fBbandwidth\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Filled by machine\&.proc_stats\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QKlipperNetworkStatsEntry::QKlipperNetworkStatsEntry (QObject * parent = \fCnullptr\fP)\fC [explicit]\fP"

.SS "QKlipperNetworkStatsEntry::QKlipperNetworkStatsEntry (const \fBQKlipperNetworkStatsEntry\fP & value)"

.SS "QKlipperNetworkStatsEntry::QKlipperNetworkStatsEntry (\fBQKlipperNetworkStatsEntry\fP && value)"

.SH "Member Function Documentation"
.PP 
.SS "qreal QKlipperNetworkStatsEntry::bandwidth () const"

.SS "void QKlipperNetworkStatsEntry::bandwidthChanged ()\fC [signal]\fP"

.SS "bool QKlipperNetworkStatsEntry::operator!= (const \fBQKlipperNetworkStatsEntry\fP & value)"

.SS "bool QKlipperNetworkStatsEntry::operator!= (\fBQKlipperNetworkStatsEntry\fP && value)"

.SS "\fBQKlipperNetworkStatsEntry\fP & QKlipperNetworkStatsEntry::operator= (const \fBQKlipperNetworkStatsEntry\fP & value)"

.SS "\fBQKlipperNetworkStatsEntry\fP & QKlipperNetworkStatsEntry::operator= (\fBQKlipperNetworkStatsEntry\fP && value)"

.SS "bool QKlipperNetworkStatsEntry::operator== (const \fBQKlipperNetworkStatsEntry\fP & value)"

.SS "bool QKlipperNetworkStatsEntry::operator== (\fBQKlipperNetworkStatsEntry\fP && value)"

.SS "qreal QKlipperNetworkStatsEntry::rxBytes () const"

.SS "void QKlipperNetworkStatsEntry::rxBytesChanged ()\fC [signal]\fP"

.SS "void QKlipperNetworkStatsEntry::setBandwidth (qreal bandwidth)\fC [slot]\fP"

.SS "void QKlipperNetworkStatsEntry::setRxBytes (qreal rxBytes)\fC [slot]\fP"

.SS "void QKlipperNetworkStatsEntry::setTxBytes (qreal txBytes)\fC [slot]\fP"

.SS "qreal QKlipperNetworkStatsEntry::txBytes () const"

.SS "void QKlipperNetworkStatsEntry::txBytesChanged ()\fC [signal]\fP"

.SH "Property Documentation"
.PP 
.SS "qreal QKlipperNetworkStatsEntry::bandwidth\fC [read]\fP, \fC [write]\fP"

.SS "qreal QKlipperNetworkStatsEntry::rxBytes\fC [read]\fP, \fC [write]\fP"

.SS "qreal QKlipperNetworkStatsEntry::txBytes\fC [read]\fP, \fC [write]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for QKlipper from the source code\&.
