.TH "QKlipperMetadata" 3 "Version 0.2" "QKlipper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QKlipperMetadata
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qklippermetadata\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator==\fP (const \fBQKlipperMetadata\fP &value)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "qreal \fBprintStartTime\fP = 0"
.br
.ti -1c
.RI "qreal \fBmodified\fP = 0"
.br
.ti -1c
.RI "qreal \fBlayerHeight\fP = 0"
.br
.ti -1c
.RI "qreal \fBfirstLayerHeight\fP = 0"
.br
.ti -1c
.RI "qreal \fBfirstLayerBedTemp\fP = 0"
.br
.ti -1c
.RI "qreal \fBfirstLayerExtruderTemp\fP = 0"
.br
.ti -1c
.RI "qreal \fBobjectHeight\fP = 0"
.br
.ti -1c
.RI "qreal \fBfilamentTotal\fP = 0"
.br
.ti -1c
.RI "qreal \fBfilamentTotalWeight\fP = 0"
.br
.ti -1c
.RI "qreal \fBnozzleDiameter\fP = 0"
.br
.ti -1c
.RI "qint32 \fBjobId\fP = 0"
.br
.ti -1c
.RI "qint64 \fBestimatedTime\fP = 0"
.br
.ti -1c
.RI "qint64 \fBgcodeStartByte\fP = 0"
.br
.ti -1c
.RI "qint64 \fBgcodeEndByte\fP = 0"
.br
.ti -1c
.RI "qint64 \fBsize\fP = 0"
.br
.ti -1c
.RI "QString \fBfilename\fP"
.br
.ti -1c
.RI "QString \fBfilamentName\fP"
.br
.ti -1c
.RI "QString \fBslicer\fP"
.br
.ti -1c
.RI "QString \fBslicerVersion\fP"
.br
.ti -1c
.RI "QString \fBuuid\fP"
.br
.ti -1c
.RI "QList< const \fBQKlipperThumbnail\fP > \fBthumbnails\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bool QKlipperMetadata::operator== (const \fBQKlipperMetadata\fP & value)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "qint64 QKlipperMetadata::estimatedTime = 0"

.SS "QString QKlipperMetadata::filamentName"

.SS "qreal QKlipperMetadata::filamentTotal = 0"

.SS "qreal QKlipperMetadata::filamentTotalWeight = 0"

.SS "QString QKlipperMetadata::filename"

.SS "qreal QKlipperMetadata::firstLayerBedTemp = 0"

.SS "qreal QKlipperMetadata::firstLayerExtruderTemp = 0"

.SS "qreal QKlipperMetadata::firstLayerHeight = 0"

.SS "qint64 QKlipperMetadata::gcodeEndByte = 0"

.SS "qint64 QKlipperMetadata::gcodeStartByte = 0"

.SS "qint32 QKlipperMetadata::jobId = 0"

.SS "qreal QKlipperMetadata::layerHeight = 0"

.SS "qreal QKlipperMetadata::modified = 0"

.SS "qreal QKlipperMetadata::nozzleDiameter = 0"

.SS "qreal QKlipperMetadata::objectHeight = 0"

.SS "qreal QKlipperMetadata::printStartTime = 0"

.SS "qint64 QKlipperMetadata::size = 0"

.SS "QString QKlipperMetadata::slicer"

.SS "QString QKlipperMetadata::slicerVersion"

.SS "QList<const \fBQKlipperThumbnail\fP> QKlipperMetadata::thumbnails"

.SS "QString QKlipperMetadata::uuid"


.SH "Author"
.PP 
Generated automatically by Doxygen for QKlipper from the source code\&.
