.TH "/home/parametheus/repo/QKlipper/QKlipperPrinter/qklippertemperaturestore.h" 3 "Version 0.2" "QKlipper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/parametheus/repo/QKlipper/QKlipperPrinter/qklippertemperaturestore.h
.SH SYNOPSIS
.br
.PP
\fC#include <QObject>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBQKlipperTemperatureStoreValue\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef QList< \fBQKlipperTemperatureStoreValue\fP > \fBQKlipperTemperatureStore\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef QList<\fBQKlipperTemperatureStoreValue\fP> \fBQKlipperTemperatureStore\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for QKlipper from the source code\&.
