.TH "QKlipperInstance" 3 "Version 0.2" "QKlipper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QKlipperInstance
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qklipperinstance\&.h>\fP
.PP
Inherits QObject\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBsetName\fP (const QString &\fBname\fP)"
.br
.ti -1c
.RI "void \fBsetAddress\fP (const QString &\fBaddress\fP)"
.br
.ti -1c
.RI "void \fBsetId\fP (const QString &\fBid\fP)"
.br
.ti -1c
.RI "void \fBsetApiKey\fP (const QString &\fBapiKey\fP)"
.br
.ti -1c
.RI "void \fBsetAutoConnect\fP (bool \fBautoConnect\fP)"
.br
.ti -1c
.RI "void \fBsetPort\fP (qint16 \fBport\fP)"
.br
.ti -1c
.RI "void \fBsetInstanceLocation\fP (const QString &\fBinstanceLocation\fP)"
.br
.ti -1c
.RI "void \fBprinterStateChanged\fP ()"
.br
.ti -1c
.RI "void \fBsetConnectionType\fP (\fBQKlipperServer::ConnectionType\fP \fBconnectionType\fP)"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBnameChanged\fP ()"
.br
.ti -1c
.RI "void \fBaddressChanged\fP ()"
.br
.ti -1c
.RI "void \fBidChanged\fP ()"
.br
.ti -1c
.RI "void \fBapiKeyChanged\fP ()"
.br
.ti -1c
.RI "void \fBautoConnectChanged\fP ()"
.br
.ti -1c
.RI "void \fBportChanged\fP ()"
.br
.ti -1c
.RI "void \fBinstanceLocationChanged\fP ()"
.br
.ti -1c
.RI "void \fBconnectionTypeChanged\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQKlipperInstance\fP (QObject *parent=nullptr)"
.br
.ti -1c
.RI "\fB~QKlipperInstance\fP ()"
.br
.ti -1c
.RI "void \fBreset\fP ()"
.br
.ti -1c
.RI "QString \fBname\fP () const"
.br
.ti -1c
.RI "QString \fBaddress\fP () const"
.br
.ti -1c
.RI "QString \fBid\fP () const"
.br
.ti -1c
.RI "QString \fBapiKey\fP () const"
.br
.ti -1c
.RI "bool \fBautoConnect\fP () const"
.br
.ti -1c
.RI "qint16 \fBport\fP () const"
.br
.ti -1c
.RI "\fBQKlipperConsole\fP * \fBconsole\fP () const"
.br
.ti -1c
.RI "\fBQKlipperServer\fP * \fBserver\fP () const"
.br
.ti -1c
.RI "\fBQKlipperSystem\fP * \fBsystem\fP () const"
.br
.ti -1c
.RI "\fBQKlipperPrinter\fP * \fBprinter\fP () const"
.br
.ti -1c
.RI "QString \fBinstanceLocation\fP () const"
.br
.ti -1c
.RI "\fBQKlipperServer::ConnectionType\fP \fBconnectionType\fP () const"
.br
.ti -1c
.RI "void \fBinit\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "QString \fBname\fP"
.br
.ti -1c
.RI "QString \fBaddress\fP"
.br
.ti -1c
.RI "QString \fBid\fP"
.br
.ti -1c
.RI "QString \fBapiKey\fP"
.br
.ti -1c
.RI "bool \fBautoConnect\fP"
.br
.ti -1c
.RI "qint16 \fBport\fP"
.br
.ti -1c
.RI "QString \fBinstanceLocation\fP"
.br
.ti -1c
.RI "\fBQKlipperServer::ConnectionType\fP \fBconnectionType\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QKlipperInstance::QKlipperInstance (QObject * parent = \fCnullptr\fP)\fC [explicit]\fP"

.SS "QKlipperInstance::~QKlipperInstance ()"

.SH "Member Function Documentation"
.PP 
.SS "QString QKlipperInstance::address () const"

.SS "void QKlipperInstance::addressChanged ()\fC [signal]\fP"

.SS "QString QKlipperInstance::apiKey () const"

.SS "void QKlipperInstance::apiKeyChanged ()\fC [signal]\fP"

.SS "bool QKlipperInstance::autoConnect () const"

.SS "void QKlipperInstance::autoConnectChanged ()\fC [signal]\fP"

.SS "\fBQKlipperServer::ConnectionType\fP QKlipperInstance::connectionType () const"

.SS "void QKlipperInstance::connectionTypeChanged ()\fC [signal]\fP"

.SS "\fBQKlipperConsole\fP * QKlipperInstance::console () const"

.SS "QString QKlipperInstance::id () const"

.SS "void QKlipperInstance::idChanged ()\fC [signal]\fP"

.SS "void QKlipperInstance::init ()"

.SS "QString QKlipperInstance::instanceLocation () const"

.SS "void QKlipperInstance::instanceLocationChanged ()\fC [signal]\fP"

.SS "QString QKlipperInstance::name () const"

.SS "void QKlipperInstance::nameChanged ()\fC [signal]\fP"

.SS "qint16 QKlipperInstance::port () const"

.SS "void QKlipperInstance::portChanged ()\fC [signal]\fP"

.SS "\fBQKlipperPrinter\fP * QKlipperInstance::printer () const"

.SS "void QKlipperInstance::printerStateChanged ()\fC [slot]\fP"

.SS "void QKlipperInstance::reset ()"

.SS "\fBQKlipperServer\fP * QKlipperInstance::server () const"

.SS "void QKlipperInstance::setAddress (const QString & address)\fC [slot]\fP"

.SS "void QKlipperInstance::setApiKey (const QString & apiKey)\fC [slot]\fP"

.SS "void QKlipperInstance::setAutoConnect (bool autoConnect)\fC [slot]\fP"

.SS "void QKlipperInstance::setConnectionType (\fBQKlipperServer::ConnectionType\fP connectionType)\fC [slot]\fP"

.SS "void QKlipperInstance::setId (const QString & id)\fC [slot]\fP"

.SS "void QKlipperInstance::setInstanceLocation (const QString & instanceLocation)\fC [slot]\fP"

.SS "void QKlipperInstance::setName (const QString & name)\fC [slot]\fP"

.SS "void QKlipperInstance::setPort (qint16 port)\fC [slot]\fP"

.SS "\fBQKlipperSystem\fP * QKlipperInstance::system () const"

.SH "Property Documentation"
.PP 
.SS "QString QKlipperInstance::address\fC [read]\fP, \fC [write]\fP"

.SS "QString QKlipperInstance::apiKey\fC [read]\fP, \fC [write]\fP"

.SS "bool QKlipperInstance::autoConnect\fC [read]\fP, \fC [write]\fP"

.SS "\fBQKlipperServer::ConnectionType\fP QKlipperInstance::connectionType\fC [read]\fP, \fC [write]\fP"

.SS "QString QKlipperInstance::id\fC [read]\fP, \fC [write]\fP"

.SS "QString QKlipperInstance::instanceLocation\fC [read]\fP, \fC [write]\fP"

.SS "QString QKlipperInstance::name\fC [read]\fP, \fC [write]\fP"

.SS "qint16 QKlipperInstance::port\fC [read]\fP, \fC [write]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for QKlipper from the source code\&.
