.TH "QKlipperUser" 3 "Version 0.2" "QKlipper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QKlipperUser
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qklipperuser\&.h>\fP
.PP
Inherits QObject\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBsetUsername\fP (const QString &\fBusername\fP)"
.br
.ti -1c
.RI "void \fBsetSource\fP (const QString &\fBsource\fP)"
.br
.ti -1c
.RI "void \fBsetCreatedOn\fP (qreal \fBcreatedOn\fP)"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBusernameChanged\fP ()"
.br
.ti -1c
.RI "void \fBsourceChanged\fP ()"
.br
.ti -1c
.RI "void \fBcreatedOnChanged\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQKlipperUser\fP (QObject *parent=nullptr)"
.br
.ti -1c
.RI "\fBQKlipperUser\fP (const \fBQKlipperUser\fP &value)"
.br
.ti -1c
.RI "\fBQKlipperUser\fP (\fBQKlipperUser\fP &&value)"
.br
.ti -1c
.RI "\fBQKlipperUser\fP & \fBoperator=\fP (const \fBQKlipperUser\fP &value)"
.br
.ti -1c
.RI "\fBQKlipperUser\fP & \fBoperator=\fP (\fBQKlipperUser\fP &&value)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBQKlipperUser\fP &value)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (\fBQKlipperUser\fP &&value)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBQKlipperUser\fP &value)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (\fBQKlipperUser\fP &&value)"
.br
.ti -1c
.RI "QString \fBusername\fP () const"
.br
.ti -1c
.RI "QString \fBsource\fP () const"
.br
.ti -1c
.RI "qreal \fBcreatedOn\fP () const"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "QString \fBusername\fP"
.br
.ti -1c
.RI "QString \fBsource\fP"
.br
.ti -1c
.RI "qreal \fBcreatedOn\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QKlipperUser::QKlipperUser (QObject * parent = \fCnullptr\fP)\fC [explicit]\fP"

.SS "QKlipperUser::QKlipperUser (const \fBQKlipperUser\fP & value)"

.SS "QKlipperUser::QKlipperUser (\fBQKlipperUser\fP && value)"

.SH "Member Function Documentation"
.PP 
.SS "qreal QKlipperUser::createdOn () const"

.SS "void QKlipperUser::createdOnChanged ()\fC [signal]\fP"

.SS "bool QKlipperUser::operator!= (const \fBQKlipperUser\fP & value)"

.SS "bool QKlipperUser::operator!= (\fBQKlipperUser\fP && value)"

.SS "\fBQKlipperUser\fP & QKlipperUser::operator= (const \fBQKlipperUser\fP & value)"

.SS "\fBQKlipperUser\fP & QKlipperUser::operator= (\fBQKlipperUser\fP && value)"

.SS "bool QKlipperUser::operator== (const \fBQKlipperUser\fP & value)"

.SS "bool QKlipperUser::operator== (\fBQKlipperUser\fP && value)"

.SS "void QKlipperUser::setCreatedOn (qreal createdOn)\fC [slot]\fP"

.SS "void QKlipperUser::setSource (const QString & source)\fC [slot]\fP"

.SS "void QKlipperUser::setUsername (const QString & username)\fC [slot]\fP"

.SS "QString QKlipperUser::source () const"

.SS "void QKlipperUser::sourceChanged ()\fC [signal]\fP"

.SS "QString QKlipperUser::username () const"

.SS "void QKlipperUser::usernameChanged ()\fC [signal]\fP"

.SH "Property Documentation"
.PP 
.SS "qreal QKlipperUser::createdOn\fC [read]\fP"

.SS "QString QKlipperUser::source\fC [read]\fP"

.SS "QString QKlipperUser::username\fC [read]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for QKlipper from the source code\&.
