.TH "QKlipperExtruder" 3 "Version 0.2" "QKlipper" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QKlipperExtruder \- \fBQKlipperExtruder\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qklipperextruder\&.h>\fP
.PP
Inherits QObject\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBsetTargetTemp\fP (qreal \fBtargetTemp\fP)"
.br
.RI "Sends a gcode script to set the requested temperature\&. "
.ti -1c
.RI "void \fBsetSmoothTime\fP (qreal \fBsmoothTime\fP)"
.br
.RI "Sends a gcode script to set the requested smooth time\&. "
.ti -1c
.RI "void \fBsetPressureAdvance\fP (qreal \fBpressureAdvance\fP)"
.br
.RI "Sends a gcode script to set the requested pressure advance\&. "
.ti -1c
.RI "void \fBsetPressureAdvanceSmoothTime\fP (qreal \fBpressureAdvanceSmoothTime\fP)"
.br
.RI "Sends a gcode script to set the requested pressure advance smooth time\&. "
.ti -1c
.RI "void \fBsetExtrusionFactor\fP (qreal \fBextrusionFactor\fP)"
.br
.RI "Sends a gcode script to set the requested extrusion factor (flow rate) "
.ti -1c
.RI "void \fBextrude\fP (qreal amount, qreal speed)"
.br
.RI "Sends a gcode script to extrude the requested length of material at the requested speed\&. "
.ti -1c
.RI "void \fBcalibratePid\fP (qreal target)"
.br
.RI "Sends a gcode script to calibrate the extruder at the target temperature\&. "
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBfanChanged\fP ()"
.br
.ti -1c
.RI "void \fBextruderNumberChanged\fP ()"
.br
.ti -1c
.RI "void \fBgearRatioChanged\fP ()"
.br
.ti -1c
.RI "void \fBfullStepsPerRotationChanged\fP ()"
.br
.ti -1c
.RI "void \fBmicrostepsChanged\fP ()"
.br
.ti -1c
.RI "void \fBcurrentTempChanged\fP ()"
.br
.ti -1c
.RI "void \fBtargetTempChanged\fP ()"
.br
.ti -1c
.RI "void \fBsmoothTimeChanged\fP ()"
.br
.ti -1c
.RI "void \fBpressureAdvanceChanged\fP ()"
.br
.ti -1c
.RI "void \fBpressureAdvanceSmoothTimeChanged\fP ()"
.br
.ti -1c
.RI "void \fBextrusionFactorChanged\fP ()"
.br
.ti -1c
.RI "void \fBfilamentDiameterChanged\fP ()"
.br
.ti -1c
.RI "void \fBnozzleDiameterChanged\fP ()"
.br
.ti -1c
.RI "void \fBpowerChanged\fP ()"
.br
.ti -1c
.RI "void \fBwattsChanged\fP ()"
.br
.ti -1c
.RI "void \fBmaxWattsChanged\fP ()"
.br
.ti -1c
.RI "void \fBinlineResistorChanged\fP ()"
.br
.ti -1c
.RI "void \fBpullupResistorChanged\fP ()"
.br
.ti -1c
.RI "void \fBpwmCycleChanged\fP ()"
.br
.ti -1c
.RI "void \fBrotationDistanceChanged\fP ()"
.br
.ti -1c
.RI "void \fBinstantCornerVelocityChanged\fP ()"
.br
.ti -1c
.RI "void \fBpidKDChanged\fP ()"
.br
.ti -1c
.RI "void \fBpidKIChanged\fP ()"
.br
.ti -1c
.RI "void \fBpidKPChanged\fP ()"
.br
.ti -1c
.RI "void \fBmaxExtrudeCrossSectionChanged\fP ()"
.br
.ti -1c
.RI "void \fBmaxExtrudeOnlyAccelerationChanged\fP ()"
.br
.ti -1c
.RI "void \fBmaxExtrudeOnlyDistanceChanged\fP ()"
.br
.ti -1c
.RI "void \fBmaxExtrudeOnlyVelocityChanged\fP ()"
.br
.ti -1c
.RI "void \fBmaxTempChanged\fP ()"
.br
.ti -1c
.RI "void \fBmaxPowerChanged\fP ()"
.br
.ti -1c
.RI "void \fBminExtrudeTempChanged\fP ()"
.br
.ti -1c
.RI "void \fBminTempChanged\fP ()"
.br
.ti -1c
.RI "void \fBcanExtrudeChanged\fP ()"
.br
.ti -1c
.RI "void \fBnameChanged\fP ()"
.br
.ti -1c
.RI "void \fBcontrolChanged\fP ()"
.br
.ti -1c
.RI "void \fBdirPinChanged\fP ()"
.br
.ti -1c
.RI "void \fBenablePinChanged\fP ()"
.br
.ti -1c
.RI "void \fBheaterPinChanged\fP ()"
.br
.ti -1c
.RI "void \fBsensorPinChanged\fP ()"
.br
.ti -1c
.RI "void \fBsensorTypeChanged\fP ()"
.br
.ti -1c
.RI "void \fBstepPinChanged\fP ()"
.br
.ti -1c
.RI "void \fBtemperatureStoreChanged\fP ()"
.br
.ti -1c
.RI "void \fBprinterChanged\fP ()"
.br
.ti -1c
.RI "void \fBoffsetChanged\fP ()"
.br
.ti -1c
.RI "void \fBconsoleChanged\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQKlipperExtruder\fP (QObject *parent=nullptr)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "\fB~QKlipperExtruder\fP ()"
.br
.RI "Destructor\&. "
.ti -1c
.RI "\fBQKlipperFan\fP * \fBfan\fP () const"
.br
.RI "The fan object associated with the extruder that is determined during the \fBQKlipperConsole\fP startup sequence\&. "
.ti -1c
.RI "qint32 \fBextruderNumber\fP () const"
.br
.RI "Toolhead index of the extruder object\&. "
.ti -1c
.RI "\fBQKlipperGearRatio\fP \fBgearRatio\fP () const"
.br
.RI "The gear ratio of the extruder\&. "
.ti -1c
.RI "qint32 \fBfullStepsPerRotation\fP () const"
.br
.RI "The number of steps it takes the stepper to complete 1 full 360 degree rotation\&. "
.ti -1c
.RI "qint32 \fBmicrosteps\fP () const"
.br
.RI "Current number of microsteps\&. "
.ti -1c
.RI "qreal \fBcurrentTemp\fP () const"
.br
.RI "Current temperature of the extruder (in Celsius) "
.ti -1c
.RI "qreal \fBtargetTemp\fP () const"
.br
.RI "Target temperature of the extruder (in Celsius) "
.ti -1c
.RI "qreal \fBsmoothTime\fP () const"
.br
.RI "Current smooth time of the extruder\&. "
.ti -1c
.RI "qreal \fBpressureAdvance\fP () const"
.br
.RI "Current pressure advance value\&. "
.ti -1c
.RI "qreal \fBpressureAdvanceSmoothTime\fP () const"
.br
.RI "Current pressure advance smooth time value\&. "
.ti -1c
.RI "qreal \fBextrusionFactor\fP () const"
.br
.RI "Current extrusion factor (flow rate) of the extruder\&. "
.ti -1c
.RI "qreal \fBfilamentDiameter\fP () const"
.br
.RI "Current filament diameter for the extruder\&. "
.ti -1c
.RI "qreal \fBnozzleDiameter\fP () const"
.br
.RI "Current nozzle diameter for the extruder\&. "
.ti -1c
.RI "qreal \fBpower\fP () const"
.br
.RI "Current power level (0\&.0-1\&.0) of the extruder's heater\&. "
.ti -1c
.RI "qreal \fBwatts\fP () const"
.br
.RI "Calculated watts of the extruders heater, based on current power level and maxWatts\&. "
.ti -1c
.RI "qreal \fBmaxWatts\fP () const"
.br
.RI "Maximum watts of the extruders heater\&. "
.ti -1c
.RI "qreal \fBinlineResistor\fP () const"
.br
.RI "Inline resistor value set in the configuration\&. "
.ti -1c
.RI "qreal \fBpullupResistor\fP () const"
.br
.RI "Pullup resistor value set in the configuration\&. "
.ti -1c
.RI "qreal \fBpwmCycle\fP () const"
.br
.RI "PWM Cycle value set in the configuration\&. "
.ti -1c
.RI "qreal \fBrotationDistance\fP () const"
.br
.RI "Rotation distance value set in the configuration\&. "
.ti -1c
.RI "qreal \fBinstantCornerVelocity\fP () const"
.br
.RI "Rotation distance value set in the configuration\&. "
.ti -1c
.RI "qreal \fBpidKD\fP () const"
.br
.RI "PID KD value set in the configuration\&. "
.ti -1c
.RI "qreal \fBpidKI\fP () const"
.br
.RI "PID KI value set in the configuration\&. "
.ti -1c
.RI "qreal \fBpidKP\fP () const"
.br
.RI "PID KP value set in the configuration\&. "
.ti -1c
.RI "qreal \fBmaxExtrudeCrossSection\fP () const"
.br
.RI "Max extrude cross section value set in the configuration\&. "
.ti -1c
.RI "qreal \fBmaxExtrudeOnlyAcceleration\fP () const"
.br
.RI "Max extrude only acceleration value set in the configuration\&. "
.ti -1c
.RI "qreal \fBmaxExtrudeOnlyDistance\fP () const"
.br
.RI "Max extrude only distance value set in the configuration\&. "
.ti -1c
.RI "qreal \fBmaxExtrudeOnlyVelocity\fP () const"
.br
.RI "Max extrude only velocity value set in the configuration\&. "
.ti -1c
.RI "qreal \fBmaxTemp\fP () const"
.br
.RI "Maximum temperature for the extruder, set in the configuration\&. "
.ti -1c
.RI "qreal \fBmaxPower\fP () const"
.br
.RI "Maximum power of the extruder heater\&. "
.ti -1c
.RI "qreal \fBminExtrudeTemp\fP () const"
.br
.RI "Minimum temperature the extruder can extrude at\&. "
.ti -1c
.RI "qreal \fBminTemp\fP () const"
.br
.RI "Minimum temperature for the extruder, set in the configuration\&. "
.ti -1c
.RI "bool \fBcanExtrude\fP () const"
.br
.RI "If the extruder can extrude material or not\&. "
.ti -1c
.RI "QString \fBname\fP () const"
.br
.RI "Name for the extruder (extruder, extruder1, etc) "
.ti -1c
.RI "QString \fBcontrol\fP () const"
.br
.RI "Control pin for the extruder, set in the configuration\&. "
.ti -1c
.RI "QString \fBdirPin\fP () const"
.br
.RI "Direction pin for the extruder, set in the configuration\&. "
.ti -1c
.RI "QString \fBenablePin\fP () const"
.br
.RI "Enable pin for the extruder, set in the configuration\&. "
.ti -1c
.RI "QString \fBheaterPin\fP () const"
.br
.RI "Heater pin for the extruder, set in the configuration\&. "
.ti -1c
.RI "QString \fBsensorPin\fP () const"
.br
.RI "Sensor pin for the extruder, set in the configuration\&. "
.ti -1c
.RI "QString \fBsensorType\fP () const"
.br
.RI "Sensor type for the extruder, set in the configuration\&. "
.ti -1c
.RI "QString \fBstepPin\fP () const"
.br
.RI "Step pin for the extruder, set in the configuration\&. "
.ti -1c
.RI "\fBQKlipperTemperatureStore\fP \fBtemperatureStore\fP () const"
.br
.RI "The temperature store provides a history of the sampled temperatures\&. "
.ti -1c
.RI "\fBQKlipperPosition\fP \fBoffset\fP () const"
.br
.RI "Offset value for the extruder as set in the configuration\&. "
.ti -1c
.RI "\fBQKlipperConsole\fP * \fBconsole\fP () const"
.br
.RI "The console object being used to send\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBQKlipperExtruder\fP class\&. 

This class provides various methods for monitoring and controlling the state of an extruder registered in the klipper instance\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QKlipperExtruder::QKlipperExtruder (QObject * parent = \fCnullptr\fP)\fC [explicit]\fP"

.PP
Constructor\&. 
.PP
\fBParameters\fP
.RS 4
\fIparent\fP The parent object 
.RE
.PP

.SS "QKlipperExtruder::~QKlipperExtruder ()"

.PP
Destructor\&. 
.SH "Member Function Documentation"
.PP 
.SS "void QKlipperExtruder::calibratePid (qreal target)\fC [slot]\fP"

.PP
Sends a gcode script to calibrate the extruder at the target temperature\&. 
.PP
\fBParameters\fP
.RS 4
\fItarget\fP The temperature to use in the PID calibration 
.RE
.PP

.SS "bool QKlipperExtruder::canExtrude () const"

.PP
If the extruder can extrude material or not\&. 
.PP
\fBReturns\fP
.RS 4
True if the extruder is ready to extrude 
.RE
.PP

.SS "void QKlipperExtruder::canExtrudeChanged ()\fC [signal]\fP"

.SS "\fBQKlipperConsole\fP * QKlipperExtruder::console () const"

.PP
The console object being used to send\&. 
.PP
\fBReturns\fP
.RS 4
The console object 
.RE
.PP

.SS "void QKlipperExtruder::consoleChanged ()\fC [signal]\fP"

.SS "QString QKlipperExtruder::control () const"

.PP
Control pin for the extruder, set in the configuration\&. 
.PP
\fBReturns\fP
.RS 4
The control pin label of the extruder 
.RE
.PP

.SS "void QKlipperExtruder::controlChanged ()\fC [signal]\fP"

.SS "qreal QKlipperExtruder::currentTemp () const"

.PP
Current temperature of the extruder (in Celsius) 
.PP
\fBReturns\fP
.RS 4
The current temperature 
.RE
.PP

.SS "void QKlipperExtruder::currentTempChanged ()\fC [signal]\fP"

.SS "QString QKlipperExtruder::dirPin () const"

.PP
Direction pin for the extruder, set in the configuration\&. 
.PP
\fBReturns\fP
.RS 4
The direction pin label of the extruder 
.RE
.PP

.SS "void QKlipperExtruder::dirPinChanged ()\fC [signal]\fP"

.SS "QString QKlipperExtruder::enablePin () const"

.PP
Enable pin for the extruder, set in the configuration\&. 
.PP
\fBReturns\fP
.RS 4
The enable pin label of the extruder 
.RE
.PP

.SS "void QKlipperExtruder::enablePinChanged ()\fC [signal]\fP"

.SS "void QKlipperExtruder::extrude (qreal amount, qreal speed)\fC [slot]\fP"

.PP
Sends a gcode script to extrude the requested length of material at the requested speed\&. 
.PP
\fBParameters\fP
.RS 4
\fIamount\fP The amount to extrude (in mm) 
.br
\fIspeed\fP The speed of the extrusion 
.RE
.PP

.SS "qint32 QKlipperExtruder::extruderNumber () const"

.PP
Toolhead index of the extruder object\&. 
.PP
\fBReturns\fP
.RS 4
The index of the extruder 
.RE
.PP

.SS "void QKlipperExtruder::extruderNumberChanged ()\fC [signal]\fP"

.SS "qreal QKlipperExtruder::extrusionFactor () const"

.PP
Current extrusion factor (flow rate) of the extruder\&. 
.PP
\fBReturns\fP
.RS 4
The current extrusion factor 
.RE
.PP

.SS "void QKlipperExtruder::extrusionFactorChanged ()\fC [signal]\fP"

.SS "\fBQKlipperFan\fP * QKlipperExtruder::fan () const"

.PP
The fan object associated with the extruder that is determined during the \fBQKlipperConsole\fP startup sequence\&. This object will change at least once, so be sure to subscribe to it's changed signal\&.
.PP
\fBReturns\fP
.RS 4
The current fan object 
.RE
.PP

.SS "void QKlipperExtruder::fanChanged ()\fC [signal]\fP"

.SS "qreal QKlipperExtruder::filamentDiameter () const"

.PP
Current filament diameter for the extruder\&. 
.PP
\fBReturns\fP
.RS 4
The current filament diameter 
.RE
.PP

.SS "void QKlipperExtruder::filamentDiameterChanged ()\fC [signal]\fP"

.SS "qint32 QKlipperExtruder::fullStepsPerRotation () const"

.PP
The number of steps it takes the stepper to complete 1 full 360 degree rotation\&. 
.PP
\fBReturns\fP
.RS 4
The current steps-per-rotation 
.RE
.PP

.SS "void QKlipperExtruder::fullStepsPerRotationChanged ()\fC [signal]\fP"

.SS "\fBQKlipperGearRatio\fP QKlipperExtruder::gearRatio () const"

.PP
The gear ratio of the extruder\&. 
.PP
\fBReturns\fP
.RS 4
A QKlipperGearRatio object 
.RE
.PP

.SS "void QKlipperExtruder::gearRatioChanged ()\fC [signal]\fP"

.SS "QString QKlipperExtruder::heaterPin () const"

.PP
Heater pin for the extruder, set in the configuration\&. 
.PP
\fBReturns\fP
.RS 4
The heater pin label of the extruder 
.RE
.PP

.SS "void QKlipperExtruder::heaterPinChanged ()\fC [signal]\fP"

.SS "qreal QKlipperExtruder::inlineResistor () const"

.PP
Inline resistor value set in the configuration\&. 
.PP
\fBReturns\fP
.RS 4
The current inline resistor value 
.RE
.PP

.SS "void QKlipperExtruder::inlineResistorChanged ()\fC [signal]\fP"

.SS "qreal QKlipperExtruder::instantCornerVelocity () const"

.PP
Rotation distance value set in the configuration\&. 
.PP
\fBReturns\fP
.RS 4
The current Rotation distance value 
.RE
.PP

.SS "void QKlipperExtruder::instantCornerVelocityChanged ()\fC [signal]\fP"

.SS "qreal QKlipperExtruder::maxExtrudeCrossSection () const"

.PP
Max extrude cross section value set in the configuration\&. 
.PP
\fBReturns\fP
.RS 4
The current Max extrude cross section value 
.RE
.PP

.SS "void QKlipperExtruder::maxExtrudeCrossSectionChanged ()\fC [signal]\fP"

.SS "qreal QKlipperExtruder::maxExtrudeOnlyAcceleration () const"

.PP
Max extrude only acceleration value set in the configuration\&. 
.PP
\fBReturns\fP
.RS 4
The current Max extrude only acceleration value 
.RE
.PP

.SS "void QKlipperExtruder::maxExtrudeOnlyAccelerationChanged ()\fC [signal]\fP"

.SS "qreal QKlipperExtruder::maxExtrudeOnlyDistance () const"

.PP
Max extrude only distance value set in the configuration\&. 
.PP
\fBReturns\fP
.RS 4
The current Max extrude only distance value 
.RE
.PP

.SS "void QKlipperExtruder::maxExtrudeOnlyDistanceChanged ()\fC [signal]\fP"

.SS "qreal QKlipperExtruder::maxExtrudeOnlyVelocity () const"

.PP
Max extrude only velocity value set in the configuration\&. 
.PP
\fBReturns\fP
.RS 4
The current Max extrude only velocity value 
.RE
.PP

.SS "void QKlipperExtruder::maxExtrudeOnlyVelocityChanged ()\fC [signal]\fP"

.SS "qreal QKlipperExtruder::maxPower () const"

.PP
Maximum power of the extruder heater\&. 
.PP
\fBReturns\fP
.RS 4
The maximum temperature of the extruder 
.RE
.PP

.SS "void QKlipperExtruder::maxPowerChanged ()\fC [signal]\fP"

.SS "qreal QKlipperExtruder::maxTemp () const"

.PP
Maximum temperature for the extruder, set in the configuration\&. 
.PP
\fBReturns\fP
.RS 4
The maximum temperature of the extruder 
.RE
.PP

.SS "void QKlipperExtruder::maxTempChanged ()\fC [signal]\fP"

.SS "qreal QKlipperExtruder::maxWatts () const"

.PP
Maximum watts of the extruders heater\&. Used to calculate current watts\&.
.PP
\fBReturns\fP
.RS 4
The maximum watts of the heater 
.RE
.PP

.SS "void QKlipperExtruder::maxWattsChanged ()\fC [signal]\fP"

.SS "qint32 QKlipperExtruder::microsteps () const"

.PP
Current number of microsteps\&. 
.PP
\fBReturns\fP
.RS 4
The current console object 
.RE
.PP

.SS "void QKlipperExtruder::microstepsChanged ()\fC [signal]\fP"

.SS "qreal QKlipperExtruder::minExtrudeTemp () const"

.PP
Minimum temperature the extruder can extrude at\&. 
.PP
\fBReturns\fP
.RS 4
The minimum extrusion temperature 
.RE
.PP

.SS "void QKlipperExtruder::minExtrudeTempChanged ()\fC [signal]\fP"

.SS "qreal QKlipperExtruder::minTemp () const"

.PP
Minimum temperature for the extruder, set in the configuration\&. 
.PP
\fBReturns\fP
.RS 4
The minimum temperature of the extruder 
.RE
.PP

.SS "void QKlipperExtruder::minTempChanged ()\fC [signal]\fP"

.SS "QString QKlipperExtruder::name () const"

.PP
Name for the extruder (extruder, extruder1, etc) 
.PP
\fBReturns\fP
.RS 4
The name of the extruder 
.RE
.PP

.SS "void QKlipperExtruder::nameChanged ()\fC [signal]\fP"

.SS "qreal QKlipperExtruder::nozzleDiameter () const"

.PP
Current nozzle diameter for the extruder\&. 
.PP
\fBReturns\fP
.RS 4
The current nozzle diameter 
.RE
.PP

.SS "void QKlipperExtruder::nozzleDiameterChanged ()\fC [signal]\fP"

.SS "\fBQKlipperPosition\fP QKlipperExtruder::offset () const"

.PP
Offset value for the extruder as set in the configuration\&. 
.PP
\fBReturns\fP
.RS 4
The current offset value 
.RE
.PP

.SS "void QKlipperExtruder::offsetChanged ()\fC [signal]\fP"

.SS "qreal QKlipperExtruder::pidKD () const"

.PP
PID KD value set in the configuration\&. 
.PP
\fBReturns\fP
.RS 4
The current PID KD value 
.RE
.PP

.SS "void QKlipperExtruder::pidKDChanged ()\fC [signal]\fP"

.SS "qreal QKlipperExtruder::pidKI () const"

.PP
PID KI value set in the configuration\&. 
.PP
\fBReturns\fP
.RS 4
The current PID KI value 
.RE
.PP

.SS "void QKlipperExtruder::pidKIChanged ()\fC [signal]\fP"

.SS "qreal QKlipperExtruder::pidKP () const"

.PP
PID KP value set in the configuration\&. 
.PP
\fBReturns\fP
.RS 4
The current PID KP value 
.RE
.PP

.SS "void QKlipperExtruder::pidKPChanged ()\fC [signal]\fP"

.SS "qreal QKlipperExtruder::power () const"

.PP
Current power level (0\&.0-1\&.0) of the extruder's heater\&. 
.PP
\fBReturns\fP
.RS 4
The current power level 
.RE
.PP

.SS "void QKlipperExtruder::powerChanged ()\fC [signal]\fP"

.SS "qreal QKlipperExtruder::pressureAdvance () const"

.PP
Current pressure advance value\&. 
.PP
\fBReturns\fP
.RS 4
The current pressure advance 
.RE
.PP

.SS "void QKlipperExtruder::pressureAdvanceChanged ()\fC [signal]\fP"

.SS "qreal QKlipperExtruder::pressureAdvanceSmoothTime () const"

.PP
Current pressure advance smooth time value\&. 
.PP
\fBReturns\fP
.RS 4
The current pressure advance smooth time 
.RE
.PP

.SS "void QKlipperExtruder::pressureAdvanceSmoothTimeChanged ()\fC [signal]\fP"

.SS "void QKlipperExtruder::printerChanged ()\fC [signal]\fP"

.SS "qreal QKlipperExtruder::pullupResistor () const"

.PP
Pullup resistor value set in the configuration\&. 
.PP
\fBReturns\fP
.RS 4
The current pullup resistor value 
.RE
.PP

.SS "void QKlipperExtruder::pullupResistorChanged ()\fC [signal]\fP"

.SS "qreal QKlipperExtruder::pwmCycle () const"

.PP
PWM Cycle value set in the configuration\&. 
.PP
\fBReturns\fP
.RS 4
The current PWM Cycle value 
.RE
.PP

.SS "void QKlipperExtruder::pwmCycleChanged ()\fC [signal]\fP"

.SS "qreal QKlipperExtruder::rotationDistance () const"

.PP
Rotation distance value set in the configuration\&. 
.PP
\fBReturns\fP
.RS 4
The current Rotation distance value 
.RE
.PP

.SS "void QKlipperExtruder::rotationDistanceChanged ()\fC [signal]\fP"

.SS "QString QKlipperExtruder::sensorPin () const"

.PP
Sensor pin for the extruder, set in the configuration\&. 
.PP
\fBReturns\fP
.RS 4
The sensor pin label of the extruder 
.RE
.PP

.SS "void QKlipperExtruder::sensorPinChanged ()\fC [signal]\fP"

.SS "QString QKlipperExtruder::sensorType () const"

.PP
Sensor type for the extruder, set in the configuration\&. 
.PP
\fBReturns\fP
.RS 4
The sensor type of the extruder 
.RE
.PP

.SS "void QKlipperExtruder::sensorTypeChanged ()\fC [signal]\fP"

.SS "void QKlipperExtruder::setExtrusionFactor (qreal extrusionFactor)\fC [slot]\fP"

.PP
Sends a gcode script to set the requested extrusion factor (flow rate) 
.PP
\fBParameters\fP
.RS 4
\fIextrusionFactor\fP The value to set (0\&.5 is 50%) 
.RE
.PP

.SS "void QKlipperExtruder::setPressureAdvance (qreal pressureAdvance)\fC [slot]\fP"

.PP
Sends a gcode script to set the requested pressure advance\&. Also sends the currently configured smooth time value\&.
.PP
\fBParameters\fP
.RS 4
\fIpressureAdvance\fP The pressure advance value to set 
.RE
.PP

.SS "void QKlipperExtruder::setPressureAdvanceSmoothTime (qreal pressureAdvanceSmoothTime)\fC [slot]\fP"

.PP
Sends a gcode script to set the requested pressure advance smooth time\&. 
.PP
\fBParameters\fP
.RS 4
\fIpressureAdvanceSmoothTime\fP The value to set 
.RE
.PP

.SS "void QKlipperExtruder::setSmoothTime (qreal smoothTime)\fC [slot]\fP"

.PP
Sends a gcode script to set the requested smooth time\&. Also sends the currently configured pressure advance value\&.
.PP
\fBParameters\fP
.RS 4
\fIsmoothTime\fP The smoothing time (in seconds) 
.RE
.PP

.SS "void QKlipperExtruder::setTargetTemp (qreal targetTemp)\fC [slot]\fP"

.PP
Sends a gcode script to set the requested temperature\&. 
.PP
\fBParameters\fP
.RS 4
\fItargetTemp\fP The value (in Celsius) to set (0-maxTemp) 
.RE
.PP

.SS "qreal QKlipperExtruder::smoothTime () const"

.PP
Current smooth time of the extruder\&. 
.PP
\fBReturns\fP
.RS 4
The current smooth time 
.RE
.PP

.SS "void QKlipperExtruder::smoothTimeChanged ()\fC [signal]\fP"

.SS "QString QKlipperExtruder::stepPin () const"

.PP
Step pin for the extruder, set in the configuration\&. 
.PP
\fBReturns\fP
.RS 4
The step pin label of the extruder 
.RE
.PP

.SS "void QKlipperExtruder::stepPinChanged ()\fC [signal]\fP"

.SS "qreal QKlipperExtruder::targetTemp () const"

.PP
Target temperature of the extruder (in Celsius) 
.PP
\fBReturns\fP
.RS 4
The target temperature 
.RE
.PP

.SS "void QKlipperExtruder::targetTempChanged ()\fC [signal]\fP"

.SS "\fBQKlipperTemperatureStore\fP QKlipperExtruder::temperatureStore () const"

.PP
The temperature store provides a history of the sampled temperatures\&. 
.PP
\fBReturns\fP
.RS 4
The temperature store object 
.RE
.PP

.SS "void QKlipperExtruder::temperatureStoreChanged ()\fC [signal]\fP"

.SS "qreal QKlipperExtruder::watts () const"

.PP
Calculated watts of the extruders heater, based on current power level and maxWatts\&. 
.PP
\fBReturns\fP
.RS 4
The current calculated watt value (0-maxWatts) 
.RE
.PP

.SS "void QKlipperExtruder::wattsChanged ()\fC [signal]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for QKlipper from the source code\&.
